### ISSUE TITLE
Can't get standalone version returning value to field

### ISSUE THREAD

**Issue by phpMagpie** [trippo/ResponsiveFilemanager#134]
Hi, I have the TinyMCE 4 version of the plugin working fine, but not able to get the standalone version working properly. 

The modal opens and I can browse through files, but when I select a file I get "Uncaught TypeError: Cannot read property 'setUrl' of null" in the console. I have tried using bootstrap modal with iframe and then tried using fancybox and same result.

If I change to dialog.php to use include.js, I can then see this error relates to line #1267 where parent.tinymce.activeEditor.windowManager.getParams() returns as null.

Thanks, Paul.

**Comment by trippo** [comment]
try with new version

**Comment by phpMagpie** [comment]
Just to let you know, rather belatedly, I've got this working ... not sure if it was linked to new version or me just having more time to solve my issue.  Thx
