### ISSUE TITLE
SERVER ERROR message in apache server

### ISSUE THREAD

**Issue by haiplk** [trippo/ResponsiveFilemanager#142]
Hi trippo,
Thanks for your sharing Reposive Filemanager, I love it and its very good for me.
But, When I upload source into server use nginx, that's ok.
Howerver, I try to upload the same source into server Apache, Its throw error when upload image (SERVER ERROR - in below image).  I try to upload another server but its error again. 
Please check about this error. 

Thank you so much.
![err2](https://cloud.githubusercontent.com/assets/7435333/5186664/6aaa370e-74fa-11e4-8a10-378cdd2a2cea.png)

![err1](https://cloud.githubusercontent.com/assets/7435333/5186647/4f804a86-74fa-11e4-83e9-548b1239ff69.png)

**Comment by arvindkoormapu** [comment]
hi
i m getting the same error...how to resolve it

**Comment by phuocpham1988** [comment]
I am getting the same SERVER ERROR. how to resolve it

**Comment by trippo** [comment]
Can you describe better the error?

**Comment by phuocpham1988** [comment]
When I upload source into localhost, that's ok.
Howerver, I try to upload the same source into hosting ( use Apache ), Its throw error when upload image (SERVER ERROR). I try to upload another server but its error again.

**Comment by trippo** [comment]
Can i have a example url?
