### ISSUE TITLE
How to disable thumbnail, and get link thumbnail when uploads

### ISSUE THREAD

**Issue by mrthinhbuzz** [trippo/ResponsiveFilemanager#148]
Sometime i dont want to use  thumbnail, so that i dont want to create thumbnail when i upload pictures
I have tried my best but i couldnt find out any ways.
And when i use thumbnail that i cant find how to take link to upload pictures.

**Comment by trippo** [comment]
thumbnails are used at this moment only inside filemenanger to display the images
