### ISSUE TITLE
SERVER ERROR on Apache upload

### ISSUE THREAD

**Issue by NiklasBr** [trippo/ResponsiveFilemanager#150]
This issue is similar to issue #142, the difference is that on my server it manages to save the file but still displays the error. The file can then be embedded using TinyMCE just as it should be, and regular bitmap images get proper thumbnails created as well.

Server configuration is as follows:

PHP 5.3.10-1ubuntu3.15 (the latest default version available on Ubuntu 12.04.5 LTS).
Apache/2.2.22 (Ubuntu)

![srv error](https://cloud.githubusercontent.com/assets/279826/5610440/ea5c8c0e-94b7-11e4-88fc-9191c68f39a7.png)

**Comment by trippo** [comment]
can i see your page online? and can i have your path configuration on config.php and your folder structure of source, thumbs and filemenanger folders?

**Comment by joe936** [comment]
+1 I have this error too. I am using this plugin with symfony 2. I setup the sources file in the public directory on ubuntu (/var/www/source/) 

configs:

$upload_dir = '/source/'; // path from base_url to base of upload folder (with start and final /)
$current_path = '/var/www/source/'; // relative path from filemanager folder to upload folder (with final /)
//thumbs folder can't put inside upload folder
$thumbs_base_path = 'source/'; // relative path from filemanager folder to thumbs folder (with final /)

The actual upload works, the file is created, but the error is displayed anyway. Also if I create a folder, the folder is created but an error is throw "source/folderName cannot be found" and the error persists preventing me from scrolling away from the error page until I go into the source folder and delete this sub folder. 

I am currently unable to display this error online (I'll work on doing that if needs be) This is happening to me on my local server(s) I have a deployment on a client's server with more or less the same config(I don't know what OS he is using though) but on the client the same code works without any problems.
