### ISSUE TITLE
the "function responsive_filemanager_callback" it not wok

### ISSUE THREAD

**Issue by chenchangwen** [trippo/ResponsiveFilemanager#158]
hi, why the "function responsive_filemanager_callback" it not work?

**Comment by trippo** [comment]
i don't know if you try my demo page work fine, i can see your code? do you have js errors?

**Comment by chenchangwen** [comment]
Thanks for your reply.i have something just now.
your online demo is no problem.
but it seems doesn't have example is "function responsive_filemanager_callback".
my code have no js errors.
i just want to do something when i uploaded the file.
thank you trippo.

**Comment by trippo** [comment]
On demo page there is this function:
```javascript
function responsive_filemanager_callback(field_id){
		console.log(field_id);
		var url=jQuery('#'+field_id).val();
		alert('update '+field_id+" with "+url);
		//your code
	}
```

if you try to select something on "Using as Stand-alone file manager" part

**Comment by chenchangwen** [comment]
ok. i will try again.thank you
