### ISSUE TITLE
Notice Undefined index: path_thumb

### ISSUE THREAD

**Issue by Libig** [trippo/ResponsiveFilemanager#159]
Hi, 
You are doing a tremendous thing!

Sometime I am getting

PHP Notice: Undefined index: path_thumb in /var/www/html/www/js/filemanager/execute.php:6  @  http://................/js/filemanager/execute.php?action=paste_clipboard

PS: domain removed.

**Comment by trippo** [comment]
can you replicate this error in my demo?

**Comment by Libig** [comment]
At the moment I am not able to reproduce it even in my implementation as I am getting this notice with some delay. As soon as I get some more info, I will be back.
