### ISSUE TITLE
Using as Stand-alone file manager when resorting files doesn't work anymore

### ISSUE THREAD

**Issue by vindic** [trippo/ResponsiveFilemanager#160]
http://www.responsivefilemanager.com/demo.php

1) Click on one of the examples of Using as Stand-alone file manager.

2) Resort files by Filename//Date//Size//Type 

3) What happens nothing, it should fill the textfield on the mainpage.

**Comment by trippo** [comment]
you are right

**Comment by trippo** [comment]
set this config:
$file_number_limit_js = 0;

**Comment by vindic** [comment]
Indeed is working, thank you for your fast response.
