### ISSUE TITLE
(new image addition) Default sort to latest images at top

### ISSUE THREAD

**Issue by seansan** [trippo/ResponsiveFilemanager#161]
Is it possible to set the program default to latest images @ top
(it is a little annoying that when you upload new image it somewhere in the middle of a huge list)

Also - would it be possible that if we double clicl (or add button insert) in the upload screen itself that we do not have to go back to the library but can insert the image immediately (from upload screen itself)

Hope it is clear

**Comment by trippo** [comment]
for sorting you can use Get Variables list in documentation

sort_by: the element to sorting (values: name,size,extension,date) default="" 
descending: descending? or ascending (values=true or false) default="false" 

Thanks for the suggestion
