### ISSUE TITLE
Change root folder when change user logged

### ISSUE THREAD

**Issue by danelsan** [trippo/ResponsiveFilemanager#164]
Hi,
I have this problem. I want to change source repository if an user logged change.
How I can do it.

Thanks

**Comment by danelsan** [comment]
I think there is error into documentation.
Into site first set
$_SESSION['RF']['subfolder']
and botton set
$_SESSION['subfolder']

I setting $_SESSION['RF']['subfolder'] and all right.

**Comment by trippo** [comment]
where do you see $_SESSION['subfolder']?

**Comment by trippo** [comment]
finded and correct. thanks
