### ISSUE TITLE
Get Server Error but file uploades successfully

### ISSUE THREAD

**Issue by imranrbx** [trippo/ResponsiveFilemanager#166]
i have configured ResponsiveFilemanger with tinyMCE editor now i have following issue that it give server error approximately i think error 500 and cross shown on image but file uploaded successfully when i click go back i can see the image file and i can use it insert it in tinymce without any problem.

![servererror](https://cloud.githubusercontent.com/assets/7753440/6637558/9349709c-c99d-11e4-956e-70c298db0cb7.png)

i hope someone can guide me to resolve this issue,

**Comment by trippo** [comment]
i think is a problem with config.php path configuration

**Comment by imranrbx** [comment]
if its issue with path configuration then how come files uploading successfully only error on thumbnails

**Comment by trippo** [comment]
i must see your folder structures and what do you put in path variables on config.php

**Comment by imranrbx** [comment]
$upload_dir = '/media/'; // path from base_url to base of upload folder (with start and final /)
$current_path = '../media/'; // relative path from filemanager folder to upload folder (with final /)
//thumbs folder can't put inside upload folder
$thumbs_base_path = '../thumbs/'; // relative path from filemanager folder to thumbs folder (with final /)
inside public_html folder i have created 2 folders with media and thumbs name and i can see thumbnails in thumbs folder
![folderstructure](https://cloud.githubusercontent.com/assets/7753440/6691778/62f6e410-ccea-11e4-96a4-ed8de0c6456e.png)

**Comment by trippo** [comment]
ok so you have the filemenanger folder at the same level of media and thumbs folders?

**Comment by imranrbx** [comment]
no filemanager is inside another folder called app folder i'm using codeigniter, is it necessary to move the filemanager folder on same level or should i move media an thumbs folders also in app folder ?

**Comment by trippo** [comment]
with this configuration you assume that is in the same level, if you don't want you must add more ../ to the  variable remember "relative path from filemanager folder to upload folder (with final /)"

**Comment by trippo** [comment]
download also new version of responsivefilemanager

**Comment by go4sandee** [comment]
Hi trippo! 

I'm facing this exact same issue using version 9.14.0. The filemanager folder is at the same level as the uploads and thumbs folder. Can this be resolved without changing the directory structure? Please help!

Thanks!

<img width="309" alt="Directory Structure" src="https://user-images.githubusercontent.com/51323886/58818623-f99d1000-864b-11e9-9b2d-7910acdd9a1c.png">
<img width="815" alt="Upload in Process" src="https://user-images.githubusercontent.com/51323886/58818625-fb66d380-864b-11e9-8f2f-ee27a3d8ddc7.png">
<img width="810" alt="Upload Complete" src="https://user-images.githubusercontent.com/51323886/58818629-fc980080-864b-11e9-85b4-c0b6eb1054b4.png">
<img width="811" alt="Return to Folder After Upload" src="https://user-images.githubusercontent.com/51323886/58818630-fdc92d80-864b-11e9-83ce-a7ebe406ba6c.png">

**Comment by trippo** [comment]
Please see the console panel at network tab the error of upload call

**Comment by go4sandee** [comment]
Hi! Console panel shows 500 internal server error. Please see attached image.
<img width="1345" alt="Internal Server Error" src="https://user-images.githubusercontent.com/51323886/59976922-ada90f80-95e8-11e9-8446-f6d9b88390d5.png">

**Comment by cakmakerhan** [comment]
( If image is successfully uploaded but return message is Internal Server Error )

It is about PHP version (after 8... )
error is : [Implicit conversion from float (number) to int loses precision]
and your error reporting is on !
php_image_magician.php  
 add "error_reporting(E_ERROR);" to top of the page, this will easly solve your problem ... have a nice day .
