### ISSUE TITLE
Integrating ResponsiveFilemanager within Codeigniter 3

### ISSUE THREAD

**Issue by KickassCoxa** [trippo/ResponsiveFilemanager#175]
Good evening. Recently i had problems while trying to integrate ResponsiveFilemanager within Codeigniter 3, because ResponsiveFilemanager uses same function names as parts of Codeigniter Core. Is there a way embeed ResponsiveFilemanager within Codeigniter controllers?

**Comment by rubenheymans** [comment]
yes, rewrite this with composer support, but that's a lot of work

**Comment by Growiel** [comment]
Same issue with Codeingiter 2. Impossible to use inside the correct /application/ folder. And that means that changing the session to use the multi user feature is also impossible...

**Comment by artipixel** [comment]
same problem, has anyone solved this issue?

**Comment by trippo** [comment]
I use in codeigniter 2 and 3 without problems, simply include on the root and use filemananger as external plugin
