### ISSUE TITLE
Passing the $_SESSION["RF"]["subfolder"] variable

### ISSUE THREAD

**Issue by PawelMysior** [trippo/ResponsiveFilemanager#178]
Hi,

In the documentation it is written that one can set the $_SESSION['RF']['subfolder'] variable and it will open a specific folder when the filemanager is invoked.

I've tried to get that to work, but with no luck. I've tried it in CakePHP 3.0 and also on a plain php file. I'm setting the variable but it doesn't get passed to the filemanager.

Any help would be greatly appreciated.

Brilliant work btw,
Pawel

**Comment by trippo** [comment]
did you try to print the sessions var in dialog.php?

**Comment by sotebuy** [comment]
I overcome it by setting the $_COOKIE['last_position'] because it didn't work anyway. The last_position should take our last position but instead it takes the first directory we selected and open the directory again and again regardless of our previous action.

**Comment by dushu2016** [comment]
in dialog.php paste the following line at line number 88 or 94
$subdir=$_GET['path'];
and path send by your view page

**Comment by trippo** [comment]
Yes but is not secure
