### ISSUE TITLE
Fancybox

### ISSUE THREAD

**Issue by jarodium** [trippo/ResponsiveFilemanager#180]
@trippo 

Hello there,
I was wondering if you are planning to drop support for fancybox for closing RFM in dialogs.
I'm asking this because I use bootbox to show RFM, I usually get errors like fancybox does not exist.

I don't know if this was solved already, but a js callback would be configured at configuration level, which would allow greater flexibility for those who are "allergic" to js errors popping up the console.

Other option was to remove fancybox calls and leave it for a callback to handle the close procedure.

**Comment by trippo** [comment]
now the script check before ask fancybox to close
