### ISSUE TITLE
issue with loading new images

### ISSUE THREAD

**Issue by thibaultvanc** [trippo/ResponsiveFilemanager#184]
Hello there !
Jus a problem when I insert new image . 
the system change the name of the file. In fact, it add the text :  %0D%0A%0D%0A%0D%0A%0D%0A
just before the real name.
for example, if I upload a file called "house.png", the returned path is : http://localhost/ambitious/%0D%0A%0D%0A%0D%0A%0D%0Ahouse.png

Is anybody has a solution to fix it ?
Thanks in advance !!!

**Comment by thibaultvanc** [comment]
in my foder, the name is corecty set to "house.png" -> the problem comes from the returned path
Any idea ?

**Comment by trippo** [comment]
this problem there is also in my demo site? if no, i think is a problem with your config.php file
