### ISSUE TITLE
flickr: SSL is required

### ISSUE THREAD

**Issue by KarelWintersky** [trippo/ResponsiveFilemanager#186]
Demo page, tinyMCE example, insert Flickr image:

check flickr accountname: 

`http://api.flickr.com/services/rest/?method=flickr.people.findByUsername&api_key=41a92923de08d07adba4057aae48c000&username=rainskylark&format=json&jsoncallback=jQuery110208804195472726518_1433173715587&_=1433173715588`

returns:
`jQuery110208804195472726518_1433173715587({"stat":"fail","code":95,"message":"SSL is required"})`

**Comment by trippo** [comment]
is not a my plugin...
