### ISSUE TITLE
Zip file Extract in Responsive File Manager error in ajax_call.php

### ISSUE THREAD

**Issue by essivision** [trippo/ResponsiveFilemanager#188]
Hi

I have problem in Extract Zip file in Responsive File Manager 9.8.2. when right click on the zip file and extract here show me this error:

Warning: copy(zip://../source/laptop.zip#images/uploads/2014/07/laptop-01.png): failed to open stream: operation failed in C:\xampp\htdocs\filemanager\ajax_calls.php on line 112
I was running file manager on the xamp in windows 7.

thanks

**Comment by trippo** [comment]
Maybe is a problem in your path configuration

**Comment by fredtempez** [comment]
Hi,
Same prob here, everything is fine except extracting zip

`Warning: copy(zip://../../../site/file/source/code.zip#code/loupe.jpg): failed to open stream: operation failed in C:\Laragon\www\ZwiiCMS\core\vendor\filemanager\ajax_calls.php on line 200`

relatif path is 'current_path' => '../../../site/file/source/', it seems to be correct according to site structure :
- root
   - core
      - vendor
       - filemanager
  - data 
     - file
        - source
Did I miss something ???
