### ISSUE TITLE
Feature Request: "Folder Select" mode

### ISSUE THREAD

**Issue by gordon-matt** [trippo/ResponsiveFilemanager#189]
Hi, I am not sure if this is the right place for a feature request, but could you please consider adding an option (example: something like type=4) for a "Folder Select" mode? I know we can right-click a folder and choose "Select" but the problem is the user might not know this and also he can still choose a file by mistake. So it would be nice if there was some option that ONLY showed folders and when the user left-clicks, then it will return that folder name (no need for right-click folder and "Select" in this mode). Maybe a tree structure would be good when opening the file manager in Folder Select mode.

**Comment by gordon-matt** [comment]
Can we look forward to this in version 9.9.5?  :-)

**Comment by gordon-matt** [comment]
I think with a little bit of work, this can easily be implemented. Now that you actually closed issue #199, I tried to do this:
&extensions=[""]

That works: it only shows folders, but no files. The problem is that the "Select" from the right-click menu does not appear anymore. I think the best thing to do is have some code to say this:

if extensions is set, but empty (""), then:
- enable the "Select" right click menu.

That is not a perfect solution, because folder select would be better if you showed a tree menu and we could left click the folder we want. But that is a lot more work... For now, I think it would be great if you could just make it that we can set extensions to [""] and then you still allow the "Select" option on the right-click menu.

**Comment by trippo** [comment]
simply remove this line 205 from dialog.php

`$_GET['type'] = 0;`

**Comment by trippo** [comment]
you must call the url to open filemananer with &type=2 mode

**Comment by gordon-matt** [comment]
That works great, thank you! I'm not sure if this item should be closed though, since that solution was not exactly what was requested. I still think that it would be best to have a proper folder select mode, where the file manager will show all folders in a hierarchy (like a tree view) and the user can left click to select a folder. That is more intuitive.

However, maybe you are saving that feature for the rewrite? In that case, I agree we can close this issue. How is the progress with writing the new one? Is it still happening?

**Comment by dico** [comment]
I also want this feature 👍
