### ISSUE TITLE
relative_url=1 does not work for folders

### ISSUE THREAD

**Issue by gordon-matt** [trippo/ResponsiveFilemanager#190]
I need relative paths for folders. The support for files works great. Please do the same for folders.

**Comment by trippo** [comment]
i fixed in version 9.9.4

**Comment by gordon-matt** [comment]
I never tried 9.9.4, so I'm not sure if you fixed it.. but I just tried this with version 9.10.1 and it's not fixed. Even when I choose a subfolder, it does not return the full path (only the name of the subfolder).

**Comment by gordon-matt** [comment]
I found the fix:
In include.js, you need to go to line 140, to comment this:
url = url.replace($('#cur_dir').val(), '');

Could you please include this fix in the next release?

**Comment by trippo** [comment]
Thanks gordon i fixed in actual 9.10.1 please re-download. I can't wait next release for this little bug
