### ISSUE TITLE
v9.9.3 Can't see text files at all

### ISSUE THREAD

**Issue by donShakespeare** [trippo/ResponsiveFilemanager#191]
With all the permissions checked, still can't view text files

**Comment by donShakespeare** [comment]
To recreate the above problem in TInyMCE 4.2, insert link, then hit the browse file button - here no text files will be seen.

But if you access the file browser directly, that is, you hit responsivefilemanager button, then all works fine

**Comment by donShakespeare** [comment]
Ah I see, what is going on; the TinyMCE plugin calls 
responsivefilemanager/filemanager/dialog.php?...&type=1...
And type 1 filters off text files

**Comment by trippo** [comment]
i don't understand this issue
