### ISSUE TITLE
Wrong images being previewed after sorting

### ISSUE THREAD

**Issue by gordon-matt** [trippo/ResponsiveFilemanager#194]
The file manager shows the wrong images in preview after sorting. This can even be seen on the official site's demo. To reproduce, try this:
1. Go to http://www.responsivefilemanager.com/demo.php
2. Find the bootstrap modal demo and click the button
3. To make this easy to see, go to a folder with a few images, I chose folder named: Test1234
4. Sort by file name in descending order
5. Click the first image and the preview will be of the last one... or click the last one and preview will be of the first one.

Hope it's a quick fix!

**Comment by trippo** [comment]
i tried and i see always correct, which browser do you use? If you have this problem set in config.php file_number_limit_js so every sort the page refresh and the sort made by php.

**Comment by gordon-matt** [comment]
Hi Alberto, I was using FireFox.. but I just tried again with Chrome as well and have the same problem. And this is not only on my local site.. i tested it with your live demo.. with FireFox and now also Chrome.

**Comment by ImXiiro** [comment]
I'm having the same sorting issue using the latest version of Safari, Firefox and Chrome on OS X.

**Comment by gordon-matt** [comment]
Almost 2 years and no fix?

**Comment by gordon-matt** [comment]
@trippo Almost 3 years and this is still a problem. To check this, go to your demos page (http://www.responsivefilemanager.com/demo.php) and then at the part where it says, "**Using as Stand-alone file manager**", click the "Open File Manager" button. Then browse to any folder with only pictures (I tested this one: **_Pics/bang mau/**).. and use your sorting button to change to ascending or descending by file name and then see what happens when you click on the first or last image.

**Comment by trippo** [comment]
to solve you can set file_number_limit_js to 0 on config.php

**Comment by trippo** [comment]
in the new version that I will release in a few days I have fixed this problem
