### ISSUE TITLE
Issue on folders

### ISSUE THREAD

**Issue by winseyli** [trippo/ResponsiveFilemanager#196]
Case 1:

Using 9.9.4 will get a blank page if there is subfolder(s) under root.
When I create a folder using ResponsiveFilemanger while no folders are there, it will be blank and never show file/folder list after I create a folder.
This does not happen on 9.9.3.

Case 2:

I set subfolder for CMS multiple user using $_SESSION["RF"]["subfolder"].
Using 9.9.4, it looks okay (can see it points to that folder as home).
But if I use root to open, I get blank page (because of case 1 issue).

**Comment by trippo** [comment]
i can't replicate your error... can you contact me on email?

**Comment by trippo** [comment]
Sorry was my error please download new version of utils.php
