### ISSUE TITLE
Allow us to set specific file types.

### ISSUE THREAD

**Issue by gordon-matt** [trippo/ResponsiveFilemanager#199]
Currently, we can use the "type" argument to specify whether RFM should show images (1), videos (3) or other files (2). While this is nice, it would be even better if there was another option to allow specific file types. For example: if I want the user to pick an EXCEL file, then I want to pass "xlsx" to the file manager.. maybe something like:
```
type=2&extensions=['xls', 'xlsx'] or just:
type=['xls', 'xlsx']
```

**Comment by trippo** [comment]
it's nice idea

**Comment by trippo** [comment]
you can add &extensions=["xls", "xlsx"] in new version 9.10.1

**Comment by gordon-matt** [comment]
Thanks, but this is not working properly. It works at first, when you load it up, but when you browse to a subfolder, it forgets the "extensions" that have been set and reverts to showing all files again.

**Comment by trippo** [comment]
yes you are right please re-download the release

**Comment by gordon-matt** [comment]
Yes, it works now. Thank you.
