### ISSUE TITLE
Error: chmod_logic not

### ISSUE THREAD

**Issue by osworx** [trippo/ResponsiveFilemanager#202]
Hello,

using the lastet version (FF 39.x) , I am getting this error when I try to edit the permissions:
``ReferenceError: chmod_logic is not defined``

E.g. line: https://github.com/trippo/ResponsiveFilemanager/blob/master/filemanager/ajax_calls.php#L394

And cannot find the function anywhere (maybe fogotten to implement).

**Comment by trippo** [comment]
You are right,
please update ajax_calls with this https://raw.githubusercontent.com/trippo/ResponsiveFilemanager/1b366b442819b10063a96dfec48bd5a635b0c40f/filemanager/ajax_calls.php 
and include.js with this:  https://infinit.io/_/3m2NRih

**Comment by osworx** [comment]
Perfect, now it works - thx.

**Comment by trippo** [comment]
please update ajax_calls file i improved layout for folder permission

**Comment by osworx** [comment]
Done, habe seen it already.
While the input field is a 'bit' big for at least 4 digits ;-)

**Comment by trippo** [comment]
:)
