### ISSUE TITLE
Browser Chrome net::ERR_INVALID_URL

### ISSUE THREAD

**Issue by allanolivei** [trippo/ResponsiveFilemanager#203]
Is not possible to save pictures edited by aviary the following message appears:

"GET data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR…AA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC?1439244731771 net::ERR_INVALID_URL"

http://www.responsivefilemanager.com/demo.php

**Comment by allanolivei** [comment]
File: php_image_magician.php
Line: 2720     
Script: if ( ! file_exists($file) && ! $this->checkStringStartsWith('http://', $file))
Erro: throw new Exception('Image not found.');

The address of aviary is HTTPS.
Solve: if ( ! file_exists($file) && (strpos($file, 'http') === false || strpos($file, 'http') > 0) )

**Comment by trippo** [comment]
Is an error of a plugin but the save work fine, your correction is done from last version from 28 july :)
