### ISSUE TITLE
input change event not trigger

### ISSUE THREAD

**Issue by Liv1020** [trippo/ResponsiveFilemanager#204]
fancyox url : /filemanager/dialog.php?type=1&field_id=editor

farentWindow has  <input name="editor" id="editor">, js : 

$('#editor').on('change', function(){
//do some thing
});

when I click image the change event not trigger

**Comment by chiendv** [comment]
DOM events not fire if elements is set via javascript. You need to mixed your js with callback function.

```javascript
$('.input-image-holder').change(function(){
	//Do something here when textbox is changed
});
function responsive_filemanager_callback(field_id){	
	$('#'+field_id).trigger('change');
}
```
Hope this  help!
