### ISSUE TITLE
chmod(): No such file or directory in error

### ISSUE THREAD

**Issue by ericfavoni** [trippo/ResponsiveFilemanager#205]
When i upload video Or audio file i see this error in input :+1: 
`http://localhost/cms/uploads/files/1/<br /><b>Warning</b>:  chmod(): No such file or directory in <b>C:\xampp\htdocs\cms\admin\templates\js\filemanager\upload.php</b> on line <b>87</b><br />Wildebeest - ArtPics - Photography - Facebook.mp4`

how do i fix this ?!

**Comment by chiendv** [comment]
Please verify that the size of file is not larger than $MaxSizeUpload in config.php and upload_max_filesize in php.ini.
I think you got this error because your file did not uploaded successfully
