### ISSUE TITLE
Multiple source image directories

### ISSUE THREAD

**Issue by Milner99** [trippo/ResponsiveFilemanager#210]
Hi,

Is it possible to have the RFM read from multiple directories? My solution currently has a "public" and "private" (for the object I'm working on) gallery of images - each stored in different directories. Is it possible to configure RFM to ready from both directories and collate the images into one selector/viewer UI?

Thanks

Chris

**Comment by trippo** [comment]
Try to use $_SESSION["RF"]["subfolder"] see the capter "SET SUBFOLDER AS ROOT AND MULTI-USER USE" on documentation
