### ISSUE TITLE
Can't copy,duplicate if rename permission set to false

### ISSUE THREAD

**Issue by henriquetorres** [trippo/ResponsiveFilemanager#211]
Hi,

Because you're using .rename-file or .rename-folder to get "data-path" there is an error when on config.php rename_files or rename_folders is set to false.

To fix this error, i've changed include.js:

all $trigger.find('.rename-file').attr('data-path'); => $trigger.find('.rename-file-paths').attr('data-path');

and all $trigger.find('.rename-folder').attr('data-path'); => $trigger.find('.rename-file-paths').attr('data-path');

Best regards

**Comment by henriquetorres** [comment]
Also there is an error on ajax_calls.php, you're using function "folderinfo" but there has been a commit on utils.php changing that function to "folder_size".
I've updated ajax_calls.php line 325 :

<code>				// size over limit
				if ($copy_cut_max_size !== false && is_int($copy_cut_max_size))
				{
					list($sizeFolderToCopy,$tmpFolderToCopy,$tmp1FolderToCopy) = folder_info($path);
					if (($copy_cut_max_size * 1024 * 1024) < $sizeFolderToCopy)
					{
						response(sprintf(trans('Copy_Cut_Size_Limit'), ($_POST['sub_action'] == 'copy' ? lcfirst(trans('Copy')) : lcfirst(trans('Cut'))), $copy_cut_max_size), 400)->send();
						exit;
					}
				}
</code>


And now it can copy, but when pasting the folder isn't created, any suggestion?

**Comment by trippo** [comment]
thanks please try with new commit
