### ISSUE TITLE
Custom theme & Bootstrap 3/4

### ISSUE THREAD

**Issue by phpMagpie** [trippo/ResponsiveFilemanager#218]
Have you thought about making the plugin more themeable?  Any advice on how to start customising the look and feel?  

I'm finding this really hard as you can't inspect any elements (context menu plugin preventing right click?).  Any way the context menu can be turned off temporarily?

I chose this plugin because it is Bootstrap based, but I only just realised it's fixed to Bootstrap 2 which is a real shame.  How difficult would it be to upgrade this to Bootstrap 3 (4 is coming out soon).

**Comment by trippo** [comment]
Actually is not simple to edit the theme but i'm rewriting all in new version

**Comment by phpMagpie** [comment]
How's the rewrite going, are you just getting started?  Will we be able to create custom themes/skins?
