### ISSUE TITLE
Watermark for ResponsiveFilemanager?

### ISSUE THREAD

**Issue by duonghien201089** [trippo/ResponsiveFilemanager#221]
I'm using ResponsiveFilemanager. I want to add my watermark on the image uploading, why it only creates thumbs picture. I need help thanks!

File utils.php

function create_img($imgfile, $imgthumb, $newwidth, $newheight = null, $option = "crop")
{
	$timeLimit = ini_get('max_execution_time');
	set_time_limit(30);
	$result = false;
	if (image_check_memory_usage($imgfile, $newwidth, $newheight))
	{
		require_once('php_image_magician.php');
		$magicianObj = new imageLib($imgfile);
		$magicianObj->addWatermark('kenhdulich.png', 'tl', 20);     // Watermark
		$magicianObj->resizeImage($newwidth, $newheight, $option);
		$magicianObj->saveImage($imgthumb, 80);
		$result = true;
	}
	set_time_limit($timeLimit);

	return $result;
}

**Comment by chiendv** [comment]
Let try with full_file_path of watermark file. I did not test but I think it works.

**Comment by trippo** [comment]
This function is called for creating thumbs or change the image dimension. to change also the images uploaded you must edit upload.php file

**Comment by jayesel** [comment]
Any direction or help on how to use this in upload.php? I can't find the right place to add the $magicianObj->addWatermark line (everywhere I try just makes the upload fail)

**Comment by trippo** [comment]
You can do what do you want after move_uploaded_file($tempFile,$targetFile);
