### ISSUE TITLE
Chrome issues v9.9.6

### ISSUE THREAD

**Issue by louisnguyen171** [trippo/ResponsiveFilemanager#222]
Chrome on 9.9.6 not run.

**Comment by trippo** [comment]
can you post the error? on eich operating system?

**Comment by louisnguyen171** [comment]
I'am testing on Chrome on MacOS and Windows 7-8.
I can't click button insert file. ( normal Filemanager window come)
But on Safari and IE is run perfect.

**Comment by trippo** [comment]
also in my demo page?

**Comment by trippo** [comment]
can you post a screenshot and the errors in js console?

**Comment by louisnguyen171** [comment]
http://app.lizi.vn/admin/index.php?Page=Newsletters&Action=Create&SubAction=Step2
user:demo - demo123
Click: Chiến dịch Email > Tạo chiến dịch > Enter Tên chiến dịch > Click "không có mẫu" > Tiếp

**Comment by louisnguyen171** [comment]
Sory about no enlish version.

**Comment by trippo** [comment]
You have a jQuery error:
```
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
```
replace $(window).innerWidth() with innerWidth and $(window). window.innerHeight()  with window.innerHeight in 
- filemanager/plugin.min.js
- tinymce folder/plugins/responsivefilemanager/plugin.min.js

**Comment by louisnguyen171** [comment]
Many thanks!!!!
Perfect
