### ISSUE TITLE
plugin.min.js

### ISSUE THREAD

**Issue by XavierFlo** [trippo/ResponsiveFilemanager#224]
I downloaded the package form github and the file "plugin.min.js" is not present in "filemanager" folder and in the "tinyMCE" plugin folder.
No prblem with the package downloaded in http://www.responsivefilemanager.com/.

Sorry if I forgot a comment somewhere.

**Comment by trippo** [comment]
the package from github is only to developers, if you want only use download zip from site.
If yu want develop or edit the code see Development doc on https://github.com/trippo/ResponsiveFilemanager
