### ISSUE TITLE
Unapplied CSS style

### ISSUE THREAD

**Issue by PetrToman** [trippo/ResponsiveFilemanager#226]
Class ``.upload-help`` in style.css does not apply to ``<div class="upload-help">`` in dialog.php (tested in Firefox).

Workaround: remove ``.upload-tabbable`` from ``.upload-tabbable .upload-help``, so that only ``.upload-help`` remains. However, the cause may be some incorrect closing of some HTML tags in dialog.php.

**Comment by trippo** [comment]
fixed in last commit
