### ISSUE TITLE
Non-localized message in dropzone

### ISSUE THREAD

**Issue by PetrToman** [trippo/ResponsiveFilemanager#227]
In dropzone, there is a message: "Drop files here to upload" that has no localization string in lang files.

Solution: add config option to dialog.php (line 293):
```
dictDefaultMessage: "<?php echo trans('Upload_message'); ?>",
```
and ``Upload_message`` key to lang files - for example cs.php would also contain:

```
'Upload_message' => "Pro nahrání přetáhněte soubor(y) sem.",
```

**Comment by trippo** [comment]
add in last commit and update release 9.9.7
