### ISSUE TITLE
Replace Java based uploader with HTML5 solution

### ISSUE THREAD

**Issue by PetrToman** [trippo/ResponsiveFilemanager#230]
Due to Java security issues it is not present on many computers. Therefore, it would be more convenient to replace Java based uploader by a pure HTML5 solution - for instance, flow.js (https://github.com/flowjs/flow.js) or resumable.js (https://github.com/23/resumable.js) libraries can be used.

**Comment by rubenheymans** [comment]
or this: https://github.com/blueimp/jQuery-File-Upload

**Comment by gavrochelegnou** [comment]
+1
I would even make that the default uploader since most of those tools have basic html fallback

**Comment by makerlabs** [comment]
I would go for https://github.com/enyo/dropzone/.

**Comment by rubenheymans** [comment]
dropzone looks great

**Comment by makerlabs** [comment]
Hmm but looking at deps its already uses dropzone so I dont fully understand why there is an additional java uploaded dropzone should have no problem with bigger files.

**Comment by PetrToman** [comment]
I'm afraid that Dropzone is limited by [post_max_size](http://php.net/post-max-size) PHP setting (which is not set high enough on most web hostings).

**Comment by gavrochelegnou** [comment]
Yes i see no mention of chunk uploads on dropzone website.
[plupload](http://www.plupload.com/) and [jquery-file-upload](https://blueimp.github.io/jQuery-File-Upload/) seems to be better candidates

**Comment by stratoss** [comment]
+1 for [jquery-file-upload](https://blueimp.github.io/jQuery-File-Upload/)
