### ISSUE TITLE
jPlayer path is incorrect in 9.9.7

### ISSUE THREAD

**Issue by cdaveb** [trippo/ResponsiveFilemanager#232]
I noticed loading errors for jPlayer when testing out upgrading to 9.9.7. It looks like in dialog.php the path to jPlayer was changed but the actual location of the file was not changed. I see the change was made in this commit:
https://github.com/trippo/ResponsiveFilemanager/commit/dc3b218da62d926a67bc63bd0764d705b95d6390

**Comment by trippo** [comment]
You are right i replaced by the last version of player. You can re-download
