### ISSUE TITLE
New folder being converted to lower case when convert spaces option is enabled

### ISSUE THREAD

**Issue by cdaveb** [trippo/ResponsiveFilemanager#233]
When the convert spaces option is enabled and the user creates a new folder, the folder name is being set to lower case. This doesn't seem logical to me- if this functionality is needed it should be controlled by a separate option and not the default implementation. I'm not sure when it was added but it would be helpful to change this to be user configurable or to remove the lower casing.

**Comment by trippo** [comment]
I tried with 'convert_spaces'                          => true and work fine

**Comment by cdaveb** [comment]
What do you mean by it worked fine? For me it's converting the spaces to 
underscores, but it is also converting the folder name to lower case. 
Are your folder names not being converted to lower case?

**Comment by trippo** [comment]
Yes you are right i re-did the test and i was wrong. 
I updated the online version with new lower_case config option
