### ISSUE TITLE
Missing insertfile.gif

### ISSUE THREAD

**Issue by robyfofo** [trippo/ResponsiveFilemanager#234]
I installed file manager 9.9.7 with tinymce 4.3.3. and everything seems to work fine, stan-alone mode and tinymce filemanager.
The only problem i have is insertfile.gif icon dont't appears in the pop-up windows tinymce (eg insert / edit image) only. In the menu's links works correct!
All path seems correct!
My installation have a custom (non standard) folder tree.
Solutions?

**Comment by trippo** [comment]
I think is a problem of path in tinymce init print your configuration and your path structure

**Comment by robyfofo** [comment]
tinymce.init({
	selector: ".contentHTML",
	theme: "modern",
	height: 300,
	language: "it",
	plugins: [
		"advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
		"searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
		"save table contextmenu directionality emoticons template paste textcolor responsivefilemanager"
	],
	relative_urls: true,
	document_base_url: window.baseUrl,
	browser_spellcheck : true ,
	filemanager_title:"Responsive Filemanager",
	external_filemanager_path: window.baseUrl+"/filemanager/",
	external_filemanager_path1: window.baseUrl+"/filemanager/",
	external_plugins: { "filemanager" : "plugins/responsivefilemanager/plugin.min.js"},
	content_css: window.baseTemplateUrl+"tinymce/css/content.css",
	image_advtab: true,
	toolbar: " undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image responsivefilemanager | print preview media fullpage | forecolor backcolor emoticons",   
	style_formats: [
		{title: 'Bold text', inline: 'b'},
		{title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
		{title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
		{title: 'Example 1', inline: 'span', classes: 'example1'},
		{title: 'Example 2', inline: 'span', classes: 'example2'},
		{title: 'Table styles'},
		{title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
	],
});

p.s.
window.baseUrl and window.baseTemplateUrl are my custom javascript vars form my framework.

window.baseUrl = 'http://192.168.1.3/framework2.6.1';
window.baseTemplateUrl='http://192.168.1.3/framework2.6.1/wscms/templates/default/';

filemanager folder is in 'http://192.168.1.3/framework2.6.1/filemanager
tinymce folder is in 'http://192.168.1.3/framework2.6.1/wscms/templates/default/tinymce

**Comment by trippo** [comment]
external_plugins must point on filemanager folder so i think window.baseUrl+"/filemanager/plugin.min.js"

**Comment by robyfofo** [comment]
Works!!! Great support! Thanks!
