### ISSUE TITLE
Empty string passed to getElementById()

### ISSUE THREAD

**Issue by djcf** [trippo/ResponsiveFilemanager#236]
Hi there,

The plugin worked fine until we moved to a new server. We have not changed the configuration at all, but now the plugin does not work -- when we click on the image, nothing in happens. In Firefox, the message 

Empty string passed to getElementById() (plugins.js:1:0)

... is displayed in the debugger.

We are using the ResponsiveFilemanager with TinyMCE, inside SocialEngine 4.

**Comment by trippo** [comment]
Is possible to see the web page?

**Comment by djcf** [comment]
It's behind a registration I'm afraid but I can make you an account. Do you 
have a preferred email address for me to send the login details to?

Thanks very much!

**Comment by trippo** [comment]
i replied in your email
