### ISSUE TITLE
Config lower_case

### ISSUE THREAD

**Issue by Jeckerson** [trippo/ResponsiveFilemanager#237]
Option lower_case => true doesn't work.
$lower_case variable doesn't appear inside ./upload.php, as well.

Current code fixes this issue.

```
$_FILES['file']['name'] = fix_filename($_FILES['file']['name'],$transliteration,$convert_spaces, $replace_with);

// Lower
if ($lower_case)
{
	$_FILES['file']['name'] = fix_strtolower($_FILES['file']['name'];
}
```

**Comment by trippo** [comment]
You are right but is lowered by js function, i also added your fix
