### ISSUE TITLE
Relative url for CKEditor

### ISSUE THREAD

**Issue by bullenb** [trippo/ResponsiveFilemanager#241]
When adding an image to CKEditor the `relative_url` option writes a path relative to the "source" folder. This path should be relative to the web root otherwise CKEditor cannot display the image. The behaviour is correct when using TinyMCE as it includes `/source/` at the beginning of the path.

**Comment by berturion** [comment]
The error is in include.js.

    var url = encodeURL((is_return_relative_url == 1 ? subdir : base_url + path) + file);

should be:

    var url = encodeURL((is_return_relative_url == 1 ? path : base_url + path) + file);

This is assuming that the url is relative to the root of your domain, and not relative to the ResponsiveFilemanager install path, which is useless.

**Comment by trippo** [comment]
thanks i put this fix in next release

**Comment by brian-hay** [comment]
This fix didn't make it in? I just ran into same issue.

Can this issue be reopened?
