### ISSUE TITLE
PHP notices when not getting folder sizes

### ISSUE THREAD

**Issue by bullenb** [trippo/ResponsiveFilemanager#244]
If `show_folder_size` is set to `false` in the config there are PHP notices displayed saying:

> Undefined variable: nfolders in filemanager/dialog.php on line 497

> Undefined variable: nfiles in filemanager/dialog.php on line 496

**Comment by trippo** [comment]
change with this:
```
$sorted[$k]=array(
			'file'=>$file,
			'file_lcase'=>strtolower($file),
			'date'=>$date,
			'size'=>$size,
			'extension'=>$file_ext,
			'extension_lcase'=>strtolower($file_ext));
		if($show_folder_size){
			$sorted[$k]['nfiles']=>$nfiles,
			$sorted[$k]['nfolders']=>$nfolders,
		}
```
I'm updating the release

**Comment by bullenb** [comment]
Excellent. Thanks for the fast work Alberto.
