### ISSUE TITLE
9.10.1 can't upload anything

### ISSUE THREAD

**Issue by smithrn** [trippo/ResponsiveFilemanager#246]
I'm using 9.10.1 with TinyMCE 4.3.7. I cannot upload any files. When I upload a file (jpg in this example) the interface puts a red X over the file and when I hover over the file:

File extension is not allowed. (@C:\Apache24\htdocs\moodle\project\tinymce\plugins\filemanager\upload.php#187)

It appears to be blocking all files.

I've used RFM for several years. 9.9.7 worked fine. In the config.php, I have minimal changes: just path changes for the file locations and Java upload disabled. I do not have any changes made to the default allowed file extensions.

**Comment by trippo** [comment]
Try to download upload.php file from github and replace
https://raw.githubusercontent.com/trippo/ResponsiveFilemanager/master/filemanager/upload.php

**Comment by smithrn** [comment]
This version works correctly. Thank you for fixing it quickly.
