### ISSUE TITLE
RFM is renaming "dotted" (hidden) directories

### ISSUE THREAD

**Issue by franksouza183** [trippo/ResponsiveFilemanager#253]
As the title says, RFM is renaming directories is that they should be hidden (unix/linux), for example, .git => file.git, .kdev4 => file.kdev4, etc. This does not happen with files. I have no idea of the purpose of this action, but please don't make the RFM to rename hidden directories.

**Comment by franksouza183** [comment]
Ok, I solved that forcing the RFM ignoring any default directory starting with ".":

In dialog.php, on line 712:

**Original:**
`if($file == '.' || (isset($file_array['extension']) && $file_array['extension']!=trans('Type_dir')) || ($file == '..' && $subdir == '') || in_array($file, $hidden_folders) || ($filter!='' && $n_files>$file_number_limit_js && $file!=".." && stripos($file,$filter)===false))`

**Adjusted:**
`if($file == '.' || ( substr($file, 0, 1) == '.' && isset( $file_array[ 'extension' ] ) && $file_array[ 'extension' ] == trans( 'Type_dir' ) ) || (isset($file_array['extension']) && $file_array['extension']!=trans('Type_dir')) || ($file == '..' && $subdir == '') || in_array($file, $hidden_folders) || ($filter!='' && $n_files>$file_number_limit_js && $file!=".." && stripos($file,$filter)===false))`

Just add the `( substr($file, 0, 1) == '.' && isset( $file_array[ 'extension' ] ) && $file_array[ 'extension' ] == trans( 'Type_dir' ) ) || ` right after `$file == '.' || `

**Comment by trippo** [comment]
thanks
