### ISSUE TITLE
Editor ERROR

### ISSUE THREAD

**Issue by msjoker** [trippo/ResponsiveFilemanager#254]
Hi, i try edit a image and give error: "There was a problem loading your image provided to the `image` config key. Either it's not actually an image file or it doesn't really exist."

Need help. ty.

**Comment by trippo** [comment]
you can't use image editor on localhot, you must are in a server because aviari must download the image.

**Comment by msjoker** [comment]
I no use localhost... You can see: http://manager.rolinedev.com/responsive_filemanager/filemanager/dialog.php

**Comment by trippo** [comment]
You have error on path configurations in config.php if you check the image url with right mouse click menu you can see http://manager.rolinedev.com/source/Logo%20Rusticae_baja.jpg and is wrong

**Comment by msjoker** [comment]
Ok!, is true... 
Old url: http://manager.rolinedev.com/responsive_filemanager/filemanager/dialog.php (ERROR)
New url: http://manager.rolinedev.com/responsive_filemanager/dialog.php (**GOOD**)

Trippo, thanks for your prompt response  (:
