### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by kennynaoh** [trippo/ResponsiveFilemanager#255]
The version in package.json is v10.0.0
But the newest version in tag is v9.10.1
Maybe should update the newest version in tag
Thanks

https://github.com/cdnjs/cdnjs/issues/7348

**Comment by trippo** [comment]
updated thanks

**Comment by kennynaoh** [comment]
It seems that it is not correct.
The version in tag is still not the same as the version in package.json
And it should be v9.10.1, not v.9.10.1
Thanks

**Comment by trippo** [comment]
What tag didi you mean?

**Comment by kennynaoh** [comment]
git tag

**Comment by kennynaoh** [comment]
Hello @trippo ,
It seems not correct.
In [git tag v.9.10.1](https://github.com/trippo/ResponsiveFilemanager/tree/v.9.10.1) , the version in [package.json](https://github.com/trippo/ResponsiveFilemanager/blob/v.9.10.1/package.json) is still 10.0.0.
Could you update that?
Thanks.

**Comment by trippo** [comment]
https://github.com/trippo/ResponsiveFilemanager/tree/v9.10.2

**Comment by kennynaoh** [comment]
Thanks.

**Comment by kennynaoh** [comment]
Oops!
https://github.com/trippo/ResponsiveFilemanager/commit/21e5eb4f8f0b62dad0ff5e2fc8bef1225c40e844
There is also a problem in title.
Version 10.9.2 ?
