### ISSUE TITLE
Which files need to be hosted

### ISSUE THREAD

**Issue by kennynaoh** [trippo/ResponsiveFilemanager#256]
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host your project on cdnjs.
But I don't know which files in this repo need to be added, could you help up find out the main files?
Thanks

**Comment by trippo** [comment]
I think is impossible to include because is a ph script there is only a few part in javascript but is integrated. I'm rewriting to separate front end and backend and after maybe will be possible.
