### ISSUE TITLE
Function set_time_limit() is not allowed on shared hostings

### ISSUE THREAD

**Issue by PetrToman** [trippo/ResponsiveFilemanager#264]
Function ``set_time_limit()`` used in ``include\utils.php``, function ``create_img()`` is not allowed on shared hostings and causes a warning - which may break RF functionality (if displaying of PHP warnings is on).

Workaround: comment out ``set_time_limit()`` calls (line 213 and 222 in ``utils.php``).

**Comment by trippo** [comment]
Thanks i fixed in the next release
