### ISSUE TITLE
How to config edit image

### ISSUE THREAD

**Issue by thanhansoft** [trippo/ResponsiveFilemanager#274]
Hi,
I'm using ResponsiveFilemanager. But I'm edit image show error:

"There was a problem loading your image provided to the `image` config key. Either it's not actually an image file or it doesn't really exist."

Please help me

**Comment by trippo** [comment]
You have an error on path or you are locally

**Comment by thanhansoft** [comment]
This is my config. Upload file success but image not show. Please help me

'upload_dir' => '/',

    /*
    |--------------------------------------------------------------------------
    | relative path from filemanager folder to upload folder
    |--------------------------------------------------------------------------
    |
    | with final /
    |
    */
    'current_path' => dirname(dirname(realpath('..'))) . '/' . $_SESSION['userFile'] . '/',

    /*
    |--------------------------------------------------------------------------
    | relative path from filemanager folder to thumbs folder
    |--------------------------------------------------------------------------
    |
    | with final /
    | DO NOT put inside upload folder
    |
    */
    'thumbs_base_path' => '../../../' . $_SESSION['userFile'] . '/.thumbs/',

**Comment by trippo** [comment]
You have a lot of errors

upload _dir => '/' . $_SESSION['userFile'] . '/source/';

'current_path' => '../../../' . $_SESSION['userFile'] . '/source/';

thumbs_base_path => '../../../' . $_SESSION['userFile'] . '/.thumbs/'
