### ISSUE TITLE
chosed in `Insert File` dialog filter affects `Insert/Edit Image` dialog (and others)

### ISSUE THREAD

**Issue by idMolotov** [trippo/ResponsiveFilemanager#288]
Steps to reproduce:
1) open `Insert File` dialog 
2) select predefined filter by clicking on the button (files) for example
3) close dialog
4) open `Insert/Edit` image dialog and click `file manager` icon near the source
5) Filemanager page will open, showing no results
Expected - that only images will be shown.

Is this correct behavior?

ps It seems, that filter selected on the main interface is stored somewhere and affects on current filter.

**Comment by trippo** [comment]
You are right i will fix in new version. To resolve add:
`if($_GET['type']==1 || $_GET['type']==3){
	$filter='';
}`

after

`if (!isset($_GET['type'])) $_GET['type'] = 0;`

in dialog.php

**Comment by idMolotov** [comment]
tnhx a lot!
