### ISSUE TITLE
Prevent Bootstrap Modal from Closing

### ISSUE THREAD

**Issue by mouse0270** [trippo/ResponsiveFilemanager#297]
Is there a way to prevent this from closing bootstrap modal after selecting a file? I just want to be able to call the callback function without the modal closing.

**Comment by mouse0270** [comment]
Nevermind, I solved my issue another way. I wanted to do this because I am using muliple dialogs to select a file. I needed to not close all of the dialogs after selecting a file.

I changed the lines 2045, 2046 & 2047 to read like this
``` javascript
if (typeof parent.$('iframe[src*="filemanager/dialog.php"]').closest('.modal').modal == "function"){
	parent.$('iframe[src*="filemanager/dialog.php"]').closest('.modal').modal('hide');
}
```
and this seems to have solved my issue.

**Comment by KarlBao** [comment]
I have the same issue. @mouse0270 

Could you tell me which file should i change? I checked some .js files and most of them are compressed.

Think would be great if there is a `preventModalClose` option...

**Comment by mouse0270** [comment]
I got the JavaScript from this github [include.js#L2045](https://github.com/trippo/ResponsiveFilemanager/blob/master/resources/assets/js/include.js#L2045) and changed the lines to what I have above then minified the script and replaced it in my project.

**Comment by trippo** [comment]
I will add in the next release

**Comment by KarlBao** [comment]
@mouse0270 Got it! Thanks so much.

**Comment by HannesOberreiter** [comment]
@trippo could we add this, had the same problem with multiple modals opened. My fix is below, but only works if you order your modals correctly, if you want to overlay them.  But the code above seems more non breaking. 

```
parent.jQuery(".modal:has(iframe)").last().modal("hide");
```

Cheers
Hannes
