### ISSUE TITLE
Video upload thumbnail creation error

### ISSUE THREAD

**Issue by PascalLiebl** [trippo/ResponsiveFilemanager#306]
Hi @trippo ,

I've tried to upload videos (with different extensions) into the filemanager but it did not work. The filemanager always returns the error: "Thumbnails creation: File extension is not allowed" and the file does not get uploaded. It does not work on your demo site either.
Is there any possible way to disable the creation of thumbnails for videos in general or can I specifically always show one particular thumbnail for every single video?
Thanks!

Cheers,
Pascal

**Comment by trippo** [comment]
Add this line to mine_type_lib.php on line 100

'mp4'     => 'video/mp4',
