### ISSUE TITLE
URL Images

### ISSUE THREAD

**Issue by Svashta** [trippo/ResponsiveFilemanager#313]
Hi,

we replaced Image plugin with RFM plugin (so Image button is not visible at all in TinyMCE), because it was confusing to users having two different means of inserting pictures.

But now, how can we add images by their URL.
In RFM URL images are actually downloaded and saved on the server.
How can users just put an URL image into the content, without special Image button?

**Comment by Svashta** [comment]
If it is not possible directly from the RFM, I can still add normal Image plugin to the toolbar, but in that case I don't want RFM icon beside image input field?

Can I remove that one?

**Comment by trippo** [comment]
Is not possible to add only a url without upload to server with RFM, if you want do that you can use only image plugin of tinymce. i think you can remove the responsivefilemanager plugin form the list of tinymce plugin.
