### ISSUE TITLE
When there are too many files, it takes a long time to open

### ISSUE THREAD

**Issue by polat** [trippo/ResponsiveFilemanager#319]
Hi,
First of all, very nice and functional plugin, thanks.

If there are not many files, no problem. But when there are too many files, it takes a long time to open. What can i do?

**Comment by trippo** [comment]
Yes is a limit, this filemanager don't use a database so every time may load watch and order all files

**Comment by trippo** [comment]
You can divide the files in multiple folders, because filemananger don't use a db so must pass in every call all files
