### ISSUE TITLE
Installing on CakePHP 3

### ISSUE THREAD

**Issue by mistaq** [trippo/ResponsiveFilemanager#328]
If I'm to install Responsive File Manager on CakePHP 3.x, do I put the extracted folder into project/vendor?

**Comment by trippo** [comment]
no is not a composer package, you can install where do you want on public root example

**Comment by mistaq** [comment]
What do you mean by Public root?

**Comment by trippo** [comment]
On root of your site

**Comment by rkaartikeyan** [comment]
@trippo If we install it in root, how it will be secure?

**Comment by rkaartikeyan** [comment]
Dear @mistaq, 

please share the details how did you integrate this in cakePHP?

**Comment by trippo** [comment]
this it's not secure I you don't limit check security paragraph on documentation
