### ISSUE TITLE
Not Enough Memory

### ISSUE THREAD

**Issue by blue-eyed-devil** [trippo/ResponsiveFilemanager#330]
There was little bug. 
- Manager upload file
- then check for php.ini limit
- if file size is greater than memory limit then delete file which is already uploaded
- otherwise create thumbnail

I think its enough to check if uploaded file exist on server. If exist then it means than no matter what is set memory limit in php.ini, because it was somehow omitted (e.g. - .htaccess settings) and therefore file is already there.

i just replaced lines (starting at line 709 in includes/utils.php

		if ($memory_needed > $memory_limit)
		{
			return false;
		}
		else
		{
			return true;
		}

WITH:

		return true;

And everything works

**Comment by linhtc** [comment]
Thank you so much

**Comment by macmuri** [comment]
If the suggestion above does not help please try to change the access rights of the destination folder.
