### ISSUE TITLE
Upload or file creation forbiden?

### ISSUE THREAD

**Issue by thewhiterabbit** [trippo/ResponsiveFilemanager#331]
I set 0777 on all the folders, but I still get message that says "forbiden" when I try to upload or create new files or folders.

![screen shot 2017-01-29 at 2 01 25 pm](https://cloud.githubusercontent.com/assets/5334222/22408300/c0f2d928-e62b-11e6-8fba-fda0c9e6a994.png)

**Comment by trippo** [comment]
You must see in the inspector on network tab the error of request, maybe is the php file forbidden

**Comment by valenti-dev** [comment]
получилось выяснить, в чем проблема?

**Comment by valenti-dev** [comment]
Нашел в чем причина, а причина именно в проверке
`!isset($_SESSION['RF']) || $_SESSION['RF']["verify"] != "RESPONSIVEfilemanager"`
которая встречается много где в коде плагина
скорее всего данная проблема встречается при использовании с CMS, которые хранят сессии нестандартными методами
у меня данная проблема наблюдалась в паре с MODX Revo
быстрый метод решения - добавить
```
if(!isset($_SESSION['RF']['verify'])) {
    $_SESSION['RF']['verify'] = 'RESPONSIVEfilemanager';
}
```
в filemanager/config/config.php после подключения сессии

**Comment by thewhiterabbit** [comment]
Closing due to age.
