### ISSUE TITLE
Incorrect function call parameters for fix_filename()

### ISSUE THREAD

**Issue by RedwingNZ** [trippo/ResponsiveFilemanager#333]
ErrorException: Illegal string offset 'transliteration'

**upload.php line 112** is calling fix_filename the old way:
$_FILES['file']['name'] = fix_filename($info['filename'].".".$extension,$transliteration,$convert_spaces, $replace_with);

The new function definition requires that the $config array is passed to it.
$_FILES['file']['name'] = fix_filename($info['filename'].".".$extension, $config);

**Comment by trippo** [comment]
you are completely right

> Il giorno 30 gen 2017, alle ore 21:47, RedwingNZ <notifications@github.com> ha scritto:
> 
> upload.php
