### ISSUE TITLE
ResponsiveFilemanager does not work with TinyMCE multi textarea

### ISSUE THREAD

**Issue by nopzixcross** [trippo/ResponsiveFilemanager#337]
I use Responsive File manager for textarea #content and #content2

then the plugin is appear only #content

my code :

`tinymce.init({
				selector: "#content2,#content", theme: "modern",
				plugins: [
				'advlist autolink lists link image charmap print preview hr anchor pagebreak',
				'searchreplace wordcount visualblocks visualchars code fullscreen',
				'insertdatetime media nonbreaking save table contextmenu directionality',
				'emoticons template paste textcolor colorpicker textpattern imagetools responsivefilemanager'
			  ],
				toolbar1: 'insertfile undo redo | styleselect | bold italic underline | forecolor backcolor | alignleft aligncenter alignright alignjustify',
				toolbar2: 'table cut copy paste searchreplace | preview media image link unlink | bullist numlist outdent indent',
				image_advtab: true,
				relative_urls: false,
				remove_script_host: false,
				convert_urls: true,
				language: 'th_TH',
				content_css : "<?php echo base_url('assets/css/tinymce.css'); ?>", 
				external_filemanager_path: "<?php echo base_url('filemanager'); ?>/",
				filemanager_title: "Filemanager",
				external_plugins: {"filemanager": "<?php echo base_url('filemanager/plugin.min.js'); ?>"},
			});`

**Comment by trippo** [comment]
Do you mean tinymce or only filemanager?

**Comment by nopzixcross** [comment]
I mean tinymce

>  trippo commented an hour ago
> Do you mean tinymce or only filemanager?

**Comment by trippo** [comment]
try to see tinymce documentation but i think you can put a class in the selector part and put the same class in the textareas

**Comment by chiendv** [comment]
Hi Trippo.
I use two TinyMCE instances on a page and filemanager only loaded and works with the last instance.
I use class for selector to init tinMce.

Any help plz?

**Comment by trippo** [comment]
Can you share with me your url?

**Comment by chiendv** [comment]
This is a backend of a website so I cant share it to you but I just use standard setup of TinyMCE and bellow is initial script

`tinyMCE.init({
						document_base_url: window.location.protocol + '//' + window.location.host+'/',
						selector: "textarea.mceEditor",
						plugins: [
							"advlist autolink lists link image charmap print preview anchor textcolor",
							"searchreplace visualblocks code fullscreen",
							"insertdatetime media table contextmenu paste"
						],
						fontsize_formats: "8pt 9pt 10pt 11pt 12pt 26pt 36pt",
						external_plugins: { "filemanager" : window.location.origin+"/filemanager/plugin.min.js"},
						toolbar: "insertfile undo redo | styleselect | fontselect | fontsizeselect | bold italic forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link responsivefilemanager",
						external_filemanager_path:"/filemanager/",
						filemanager_access_key: RESPONSIVE_FMG_TOKEN ,
						autosave_ask_before_unload: false,	
						relative_urls: true,
						//convert_urls: false,
						remove_script_host: true,
						theme: 'modern',
						min_height: 160,
						height : 500
					});	`

**Comment by chiendv** [comment]
more information for you, Trippo
it works in TinyMce version 4.2.8 but not in latest 4.6.1

**Comment by trippo** [comment]
I tried in my demo page and work fine also in 4.6.1

<textarea class="tinymce" id="normal"></textarea>
<textarea class="tinymce" id="second"></textarea>

tinymce.init({
    selector: "textarea.tinymce",...

**Comment by nesumneno** [comment]
Hi,
I have the same issue. Can you tell me please if you managed to fix this problem?

**Comment by trippo** [comment]
https://github.com/trippo/ResponsiveFilemanager/issues/357#issuecomment-310637765

**Comment by chinhnguyenitvn** [comment]
@chiendv , the same issue, could you fixed it

**Comment by HTibor87** [comment]
Async problem.
**Initialize separately and wait for 1 second between initialization.**
