### ISSUE TITLE
new fancybox compatibility

### ISSUE THREAD

**Issue by blue-eyed-devil** [trippo/ResponsiveFilemanager#345]
There is new fancybox v3+ released. All seems to work fine, the only thing that does not work is that lightbox is not closed when file is selected in standalone mode. Can anyone tell how o fix it? thanks

**Comment by trippo** [comment]
you must edit close_window function in include.js

**Comment by aris-kun** [comment]
have the same problem, can't close fancybox after select the file. I'm trying to edit close_window function  in include.js but I can't found it.

**Comment by trippo** [comment]
You must edit the no compressed file on resource folder in github

**Comment by aris-kun** [comment]
So, do i have to change
```javascript
parent.jQuery.fancybox.close(); // line 2104 in include.js
```
to be like this?
```javascript
// Close current fancyBox instance
parent.jQuery.fancybox.getInstance().close();
```

**Comment by trippo** [comment]
I think yes

**Comment by aris-kun** [comment]
still not working after I change to this
```javascript
	function close_window()
	{
		if (jQuery('#popup').val() == 1)
		{
			window.close();
		}
		else
		{
			if (typeof parent.jQuery('.modal').modal == "function"){
				parent.jQuery('.modal').modal('hide');
			}
			if (typeof parent.jQuery !== "undefined" && parent.jQuery)
			{
				if(typeof parent.jQuery.fancybox == 'function'){
					parent.jQuery.fancybox.getInstance().close();
				}
			}
			else
			{
				if(typeof parent.$.fancybox == 'function'){
					parent.$.fancybox.getInstance().close();
				}
			}
		}
	}

	function close_window()
	{
		if (jQuery('#popup').val() == 1)
		{
			window.close();
		}
		else
		{
			if (typeof parent.jQuery(".modal:has(iframe[src*=filemanager])").modal == "function"){
				parent.jQuery(".modal:has(iframe[src*=filemanager])").modal("hide");
			}
			if (typeof parent.jQuery !== "undefined" && parent.jQuery)
			{
				if(typeof parent.jQuery.fancybox == 'function'){
					parent.jQuery.fancybox.getInstance().close();
				}
			}
			else
			{
				if(typeof parent.$.fancybox == 'function'){
					parent.$.fancybox.getInstance().close();
				}
			}
		}
	}
```

**Comment by aris-kun** [comment]
### update

after I delete all close_window function and then create one like this
```javascript
function close_window()
	{
		parent.jQuery.fancybox.getInstance().close();
	}
```
finally, fancybox close after selecting file

**Comment by cdaveb** [comment]
The reason your change didn't work aris-kun is that you were checking for a type of function, but for Fancybox 3 it's actually a type of object. I've made a modified version of the close window code for my implementation that maintains the older Fancybox compatibility while adding support for 3.x.

`
    function close_window()
    {
        if (jQuery('#popup').val() == 1)
        {
            window.close();
        }
        else
        {
            if (typeof parent.jQuery('.modal').modal == "function"){
                parent.jQuery('.modal').modal('hide');
            }
            if (typeof parent.jQuery !== "undefined" && parent.jQuery)
            {
                if (typeof parent.jQuery.fancybox == 'object'){
                    parent.jQuery.fancybox.getInstance().close();
                }
                else if(typeof parent.jQuery.fancybox == 'function'){
                    parent.jQuery.fancybox.close();
                }
            }
            else
            {
                if(typeof parent.$.fancybox == 'function'){
                    parent.$.fancybox.close();
                }
            }
        }
    }

    function close_window()
    {
        if (jQuery('#popup').val() == 1)
        {
            window.close();
        }
        else
        {
            if (typeof parent.jQuery(".modal:has(iframe[src*=filemanager])").modal == "function"){
                parent.jQuery(".modal:has(iframe[src*=filemanager])").modal("hide");
            }
            if (typeof parent.jQuery !== "undefined" && parent.jQuery)
            {
                if (typeof parent.jQuery.fancybox == 'object'){
                    parent.jQuery.fancybox.getInstance().close();
                }
                else if(typeof parent.jQuery.fancybox == 'function'){
                    parent.jQuery.fancybox.close();
                }
            }
            else
            {
                if(typeof parent.$.fancybox == 'function'){
                    parent.$.fancybox.close();
                }
            }
        }
    }
`

**Comment by aris-kun** [comment]
thank you @cdaveb , I'll try your code 😄 👍

**Comment by trippo** [comment]
thanks i'll implement in new version
