### ISSUE TITLE
9.11.3 - When using multiple instancef of TinyMCE filemanager avilable only on last instance (since TinyMce 4.6.0)

### ISSUE THREAD

**Issue by kociou** [trippo/ResponsiveFilemanager#357]
```
<script>
//first instance
tinymce.init({
        "theme": "modern",
        "plugins": ["advlist autolink lists link image charmap print preview hr anchor pagebreak", "searchreplace wordcount visualblocks visualchars code fullscreen", "insertdatetime media nonbreaking save table contextmenu directionality", "template paste textcolor"],
        "toolbar1": "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | media | forecolor backcolor code",
        "toolbar2": false,
        "image_advtab": true,
        "height": "450",
        "statusbar": false,
        "external_filemanager_path": "/static-local/filemanager/",
        "filemanager_title": "Manager",
        "external_plugins": {
            "filemanager": "/static-local/filemanager/plugin.min.js"
        },
        "extended_valid_elements": "blockquote[class,style],a[class|name|href|target|title|onclick|rel],script[type|src],iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder|class],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name]",
        "browser_spellcheck": true,
        "contextmenu": false,
        "selector": "#text_pl-PL",
        "language_url": "/static-local/assets/6a5e4690/langs/pl.js",
        "language": "pl"
    });


//secound instance
    tinymce.init({
        "theme": "modern",
        "plugins": ["advlist autolink lists link image charmap print preview hr anchor pagebreak", "searchreplace wordcount visualblocks visualchars code fullscreen", "insertdatetime media nonbreaking save table contextmenu directionality", "template paste textcolor"],
        "toolbar1": "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | media | forecolor backcolor code",
        "toolbar2": false,
        "image_advtab": true,
        "height": "450",
        "statusbar": false,
        "external_filemanager_path": "/static-local/filemanager/",
        "filemanager_title": "Manager",
        "external_plugins": {
            "filemanager": "/static-local/filemanager/plugin.min.js"
        },
        "extended_valid_elements": "blockquote[class,style],a[class|name|href|target|title|onclick|rel],script[type|src],iframe[src|style|width|height|scrolling|marginwidth|marginheight|frameborder|class],img[class|src|border=0|alt|title|hspace|vspace|width|height|align|onmouseover|onmouseout|name]",
        "browser_spellcheck": true,
        "contextmenu": false,
        "selector": "#text_en-US",
        "language_url": "/static-local/assets/6a5e4690/langs/pl.js",
        "language": "pl"
    });
</script>
```

**Comment by MichalSchwarz** [comment]
I have the same problem.

**Comment by perezdans** [comment]
Yes, me too.

**Comment by Fridus** [comment]
Same problem !

**Comment by Fridus** [comment]
@trippo Could you quickly fix this ? 🙏

**Comment by gulaandrij** [comment]
same

**Comment by trippo** [comment]
Hi is a problem of tinymce i think they are envious of my filemanager... 
I'm investigating... but you can use the responsivefilemananger plugin 
![schermata 2017-06-23 alle 12 16 25](https://user-images.githubusercontent.com/497169/27477909-fa717afc-580d-11e7-9f5a-a9d81382f470.jpg)

**Comment by trippo** [comment]
Please also you write to tinymce support to have a reply @gulaandrij @Fridus @perezdans @MichalSchwarz @kociou

**Comment by trippo** [comment]
I found a solution... you can include the filemanager call inside new api es:

`
filemanager_title:"Responsive Filemanager",
    external_filemanager_path:"/filemanager/",
    file_picker_types: 'file image media',
    file_picker_callback: function(cb, value, meta) {
	    var width = window.innerWidth-30;
		var height = window.innerHeight-60;
		if(width > 1800) width=1800;
		if(height > 1200) height=1200;
		if(width>600){
			var width_reduce = (width - 20) % 138;
			width = width - width_reduce + 10;
		}
	    var urltype=2;
		if (meta.filetype=='image') { urltype=1; }
		if (meta.filetype=='media') { urltype=3; }
		var title="RESPONSIVE FileManager";
		if (typeof this.settings.filemanager_title !== "undefined" && this.settings.filemanager_title) {
			title=this.settings.filemanager_title;
		}
		var akey="key";
		if (typeof this.settings.filemanager_access_key !== "undefined" && this.settings.filemanager_access_key) {
			akey=this.settings.filemanager_access_key;
		}
		var sort_by="";
		if (typeof this.settings.filemanager_sort_by !== "undefined" && this.settings.filemanager_sort_by) {
			sort_by="&sort_by="+this.settings.filemanager_sort_by;
		}
		var descending="false";
		if (typeof this.settings.filemanager_descending !== "undefined" && this.settings.filemanager_descending) {
			descending=this.settings.filemanager_descending;
		}
		var fldr="";
		if (typeof this.settings.filemanager_subfolder !== "undefined" && this.settings.filemanager_subfolder) {
			fldr="&fldr="+this.settings.filemanager_subfolder;
		}
		var crossdomain="";
		if (typeof this.settings.filemanager_crossdomain !== "undefined" && this.settings.filemanager_crossdomain) {
			crossdomain="&crossdomain=1";

			// Add handler for a message from ResponsiveFilemanager
			if(window.addEventListener){
				window.addEventListener('message', filemanager_onMessage, false);
			} else {
				window.attachEvent('onmessage', filemanager_onMessage);
			}
		}
	    tinymce.activeEditor.windowManager.open({
			title: title,
			file: this.settings.external_filemanager_path+'dialog.php?type='+urltype+'&descending='+descending+sort_by+fldr+crossdomain+'&lang='+this.settings.language+'&akey='+akey,
			width: width,
			height: height,
			resizable: true,
			maximizable: true,
			inline: 1
			}, {
			setUrl: function (url) {
				cb(url);
			}
		});
	},
`

**Comment by TomTheRock** [comment]
I had the same problem, i downgrade to tinymce 4.5.7 now it worked as in the past. But anybody have a solution with the new version. I cant find the documentation for the api method on tinymce website....*eyesroll*

**Comment by defender11** [comment]
**TomTheRock:** Can you write how you got (code)?

**Comment by defender11** [comment]
**TomTheRock:** Where did you find tinyMce 4.5.7? (site)

**Comment by Fridus** [comment]
@defender11 http://download.ephox.com/tinymce/community/tinymce_4.5.7.zip 🙈

**Comment by defender11** [comment]
@Fridus Thanks man!

**Comment by TomTheRock** [comment]
You can always find later releases here: https://www.tinymce.com/download/older-releases/

**Comment by defender11** [comment]
@TomTheRock I did`t know this, thank you man!

**Comment by TomTheRock** [comment]
Bug is postet on git (tinymce)
https://github.com/tinymce/tinymce/issues/3764

**Comment by labby** [comment]
This solution works for us inside LEPTON-CMS:
place following code inside tinymce.init({:
`   file_browser_callback: function(fieldName, url, objectType, w) {
        filemanager(fieldName, url, objectType, w);
    },`
Hope this will also help others...

**Comment by InfinityWebMe** [comment]
https://github.com/trippo/ResponsiveFilemanager/issues/357#issuecomment-322513978 work with second instance but not the first.

https://github.com/trippo/ResponsiveFilemanager/issues/357#issuecomment-310637765 work with all instance.
