### ISSUE TITLE
Problem file url

### ISSUE THREAD

**Issue by Ricco-S** [trippo/ResponsiveFilemanager#358]
Hello i have a problem with file url 

The file path in the editor looks like this: ../source/folder/file.jpg.  and runs and display file in editor.

But when i post content the src in page looks like 
this:  ../../source/folder/file.jpg. 

What i need is  change this to:
 http://domain.com/folder/source/folder/file.jpg. 
Someone an idea how to ?

**Comment by aris-kun** [comment]
if you using tinymce, try to add this options

```javascript
tinymce.init({
	...
	relative_urls: false,
	convert_urls: false,
	remove_script_host : false,
	image_prepend_url: "your base url"
	...
});
```

**Comment by BjornMelgaard** [comment]
fuck yeah, @arispati !!!!!!!!!!! 

`convert_urls:       false,` worked for me with `'base_url' => '',`

thankuuuuu!
