### ISSUE TITLE
Upload big image, like 3000x3000

### ISSUE THREAD

**Issue by LandarOne** [trippo/ResponsiveFilemanager#362]
Hello. There is one similar issue, closed: [https://github.com/trippo/ResponsiveFilemanager/issues/37](url)
I have version 9.11.3 (last). When I want to upload JPG with resolution 4928x3264 Px (6-10MB) then it start with uploading and end with message: Not enough memory: upload.php:241. But I already changed "MaxSizeUpload" (to 19MB, accrording to server info). When I try to upload ZIP file with 15MB ok, no problem. Images under 3000x3000 Px are also ok, no problem. So it is not task of MB size but Px size of image. On the link where is similar issue I found old solutions, which is already in "utils.php" - line 697. But I try to change code by this way: 

`//original: $memory_limit = abs(intval(str_replace('M', '', ini_get('memory_limit')) * 1024 * 1024));
$memory_limit = abs(intval(str_replace('M', '', ini_get('memory_limit')) * 8192 * 6144));  //new (ok) `

When I do this "increase of Px" so upload start working fine also for bigger JPGs resolution - no error message and image is uploaded (I dont use resize or other functions, just uploading).

Is my way of change ok, and is the "1024 * 1024" pixel definition?
(or what to do else for correct bigger image upload?)

**Comment by KarelWintersky** [comment]
I have a same issue. And solved this problem.

See below:
```
function image_check_memory_usage($img, $max_breedte, $max_hoogte)
{
	if (file_exists($img))
	{
		$K64 = 65536; // number of bytes in 64K
		$memory_usage = memory_get_usage();
		$memory_limit = abs(intval(str_replace('M', '', ini_get('memory_limit')) * 1024 * 1024));
		$image_properties = getimagesize($img);
		$image_width = $image_properties[0];
		$image_height = $image_properties[1];
		if (isset($image_properties['bits']))
			$image_bits = $image_properties['bits'];
		else
			$image_bits = 0;

		var_dump($image_width, $image_height, ($image_bits >> 3) * 2);

		$image_memory_usage = $K64 + ($image_width * $image_height * ($image_bits) * 2);
		$thumb_memory_usage = $K64 + ($max_breedte * $max_hoogte * ($image_bits) * 2);
		$memory_needed = abs(intval($memory_usage + $image_memory_usage + $thumb_memory_usage));
```

Image Memory Usage IS: 
IMAGE WIDTH * IMAGE HEIGHT * 2 * IMAGE BITS

If you have 8bit image - width*height will be multiplied by 16. 
If you have 16bit image - width*height will be multiplied by 32. 

I do not know what kind of moron must be to mix bits and bytes ...

Correct code ARE:

```
		$image_memory_usage = $K64 + ($image_width * $image_height * ($image_bits >> 3) * 2);
		$thumb_memory_usage = $K64 + ($max_breedte * $max_hoogte * ($image_bits >> 3) * 2);
```

**Comment by trippo** [comment]
thanks i'll add in new update
