### ISSUE TITLE
Fit function "image_check_memory_usage()" to settings memory_limit = -1

### ISSUE THREAD

**Issue by wllfl** [trippo/ResponsiveFilemanager#369]
When php.ini is with memory_limit -1, the "image_check_memory_usage ()" function multiplies (-1 * 1024 * 1024), which is unlimited memory.

**Comment by trippo** [comment]
The last versio have this function:

function image_check_memory_usage($img, $max_breedte, $max_hoogte)
{
	if (file_exists($img))
	{
		$K64 = 65536; // number of bytes in 64K
		$memory_usage = memory_get_usage();
		if(ini_get('memory_limit') > 0 ){
			$memory_limit = abs(intval(str_replace('M', '', ini_get('memory_limit')) * 1024 * 1024));
			$image_properties = getimagesize($img);
			$image_width = $image_properties[0];
			$image_height = $image_properties[1];
			if (isset($image_properties['bits']))
				$image_bits = $image_properties['bits'];
			else
				$image_bits = 0;
			$image_memory_usage = $K64 + ($image_width * $image_height * ($image_bits) * 2);
			$thumb_memory_usage = $K64 + ($max_breedte * $max_hoogte * ($image_bits) * 2);
			$memory_needed = abs(intval($memory_usage + $image_memory_usage + $thumb_memory_usage));

			if ($memory_needed > $memory_limit)
			{
				return false;
			}
		}
		return true;
	}
	else
	{
		return false;
	}
}
