### ISSUE TITLE
SERVER ERROR

### ISSUE THREAD

**Issue by EmanuelAzzopardi** [trippo/ResponsiveFilemanager#370]
Thanks for a lot for responsive file manager. I had used for the first time in 2016 in combination with tiynMCE, It was working fine and my friend who owns this website (http://ilbettija.com.mt/news/singleNewsPost.php?id=63) create a couple of news feeds. Recently I found that the older version I had install is no longer working and was throwing several php errors such as the following. 

Warning: filesize(): stat failed for ../source/Tom/-BosWeb in /home/ilbeffls/public_html/file_manager/filemanager/include/utils.php on line

I view of this I had downloaded the latest release and removed the old version. MY configuration on localhost and on server are the following:

TinyMCE
- root/tinyMCE
TinyMCE is configured wiht the following parmeters;
	- external_filemanager_path:"../file_manager/filemanager/",
	- filemanager_title:"Responsive Filemanager" ,
	- external_plugins: { "filemanager" : "/file_manager/filemanager/plugin.min.js"},
	- relative_urls : false,
	- remove_script_host : true,
	- document_base_url : '../'

FileManager
root/file_manager/(file manger download files). The config file is configured as follows. 

	/*
	|--------------------------------------------------------------------------
	| DON'T TOUCH (base url (only domain) of site).
	|--------------------------------------------------------------------------
	|
	| without final / (DON'T TOUCH)
	|
	*/
	'base_url' => ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] && ! in_array(strtolower($_SERVER['HTTPS']), array( 'off', 'no' ))) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'],

	/*
	|--------------------------------------------------------------------------
	| path from base_url to base of upload folder
	|--------------------------------------------------------------------------
	|
	| with start and final /
	|
	*/
	'upload_dir' => '/file_manager/source/',
	/*
	|--------------------------------------------------------------------------
	| relative path from filemanager folder to upload folder
	|--------------------------------------------------------------------------
	|
	| with final /
	|
	*/
	'current_path' => '../source/',

	/*
	|--------------------------------------------------------------------------
	| relative path from filemanager folder to thumbs folder
	|--------------------------------------------------------------------------
	|
	| with final /
	| DO NOT put inside upload folder
	|
	*/
	'thumbs_base_path' => '../thumbs/',

The problem is that on the LOCALHOST I managed to upload the images however on the SERVER I fail to do so. The progress bar gets loaded, but then I get a SERVER ERROR. I am prettry surre that the above config settings are correct as yesterday I managed to upload an image via URL and the file was copied both in the source as well as in the thumbs folder. I there somehting else whihc I might need to configure?

Many thanks

**Comment by trippo** [comment]
i replied on your email

**Comment by EmanuelAzzopardi** [comment]
thanks
