### ISSUE TITLE
Add callback for use in TinyMCE after selecting file

### ISSUE THREAD

**Issue by trevorhawes** [trippo/ResponsiveFilemanager#376]
When you select a file but before it is inserted into TinyMCE 4, I need a callback so I can do something special with the file/html before insertion.

trevorhawes1@gmail.com

**Comment by trippo** [comment]
You must see if is possible on tinymce documentation, or you can call a callack in plugin.min.js script of responsivefilemanager folder... on GitHub resource folder you can have not minified version
