### ISSUE TITLE
Upload tab not working and problem with image edit tools

### ISSUE THREAD

**Issue by philouphil** [trippo/ResponsiveFilemanager#381]
Hello,

First a really really big thanx for your file manager which is impressive !

I just have two problems to solve before I can drink a bottle of "Champagne" or "Prosecco" (I guess you're italian :-)) and I think in fact this just two results of the same misconfiguration.

I use last version of file manager and last version of tinymce.

First problem : when I try to uplaod an image via the upload tab, I got an endless loading (you cant see on the picture, just to show you which tab it is)

![upload_tab](https://user-images.githubusercontent.com/5773627/30585497-5be4ed14-9d2d-11e7-99ea-f2de73afc225.jpg)

Second problem : I don't want to use blob fonctionnality when I edit an image via the image tools options, I would prefer to overwrite the original image with the modified one. So when I click the save button in the image tools panel, tinymce show in that example a cropped version of Koala and the message "Image uploading ...100%" that never desappears ... the process is stucked.

![koala](https://user-images.githubusercontent.com/5773627/30585935-a2dedcba-9d2e-11e7-9e4f-534046c4341f.jpg)

Here is my environment : 
-data
-filemanager
-tinymce 
[filemanager.zip](https://github.com/trippo/ResponsiveFilemanager/files/1313732/filemanager.zip)

and this is my tinymce edit code which is at the root level (same level as the three folders)
`<script>
	  tinymce.init({
		selector: "textarea",
		height: 400,
		language: 'fr_FR',
		relative_urls: true,
		plugins: [
			 "advlist autolink link image imagetools lists charmap print preview hr",
			 "searchreplace wordcount visualblocks visualchars media",
			 "table contextmenu directionality emoticons paste textcolor responsivefilemanager code"
	   ],
	   toolbar1: "undo redo | styleselect | bold italic underline | alignleft aligncenter alignright | bullist outdent indent | forecolor backcolor removeformat | hr | unlink link  | media image responsivefilemanager",
	   image_advtab: true ,
	   external_filemanager_path:"filemanager/",
	   filemanager_title:"Medias" ,
	   external_plugins: { "filemanager" : "../filemanager/plugin.min.js"},
	   images_upload_url: 'filemanager/upload_image.php',
	   images_upload_base_path: '/data/users',
	   automatic_uploads: true,
	   images_reuse_filename: true
	 });
	</script>`

Thank you for your help !!

**Comment by trippo** [comment]
This is a tinymce image upload not responsive filemanager upload
