### ISSUE TITLE
tinymce.activeEditor.windowManager.getParams(...).setUrl is not a function

### ISSUE THREAD

**Issue by cfconsultancy** [trippo/ResponsiveFilemanager#386]
tinymce.activeEditor.windowManager.getParams(...).setUrl is not a function include.js in the latest tinymce version, Version 4.6.7 tinymce.min.js no CDN all browsers.

Version 4.6.6 (and older) works correct.
Filed the bug at tinymce but they think it is plugin related

**Comment by cleblond** [comment]
I have the same issue.

**Comment by dmonteirosouza** [comment]
I have the same issue too

**Comment by cfconsultancy** [comment]
Seems to be solved in the latest tinyMCE 4.7.0
