### ISSUE TITLE
Cannot open folder. I click on the folder and it does Refresh

### ISSUE THREAD

**Issue by Flasker99** [trippo/ResponsiveFilemanager#388]
Hello guys,

I have problem with responsive file manger.

In tinymce a use plugin, and a click de icon and open pop up. Show everthing correct just cannot open folder. I click on the folder and it does Refresh.

This is my config tinymce

 external_filemanager_path:"<?php echo $base_url;?>filemanager/",
            relative_urls: false,
            document_base_url: '<?php echo $base_url;?>',
            filemanager_title:"Responsive File Manager" ,
            external_plugins: { "filemanager" : "<?php echo $base_url;?>filemanager/plugin.min.js"}

**Comment by trippo** [comment]
can i see you page? on my demo page work correctly?

**Comment by fsabreu** [comment]
Hello everyone,
I am having the same problem.

I'm using
RESPONSIVE filemanager v.9.14.0
Tinymce 4.7.3
PHP 7.3.12

I can create a folder, but when I try to open it the page reloads and goes back to the root.

Has anyone managed to solve this problem?

Thanks and congratulations for the work @trippo
