### ISSUE TITLE
I don't have scroll if I open using fancybox3.

### ISSUE THREAD

**Issue by shurupov** [trippo/ResponsiveFilemanager#392]
ResponsiveFileManager : 9.11.3

![03 10 2017_003_w1036_h697](https://user-images.githubusercontent.com/421268/31146526-1e89994e-a898-11e7-91ed-a75986288b7a.png)

List is not full and threre is no scrolls in the right.

Tried in Chrome, Firefox and Opera

**Comment by trippo** [comment]
How do you open the file manager? in modal? i think the problem is your container because work fine in my tests.
