### ISSUE TITLE
Upload not working to seted root folder

### ISSUE THREAD

**Issue by FelipeDossiLima** [trippo/ResponsiveFilemanager#399]
Hi! Great job with responsive file manager.
I want to report a problem I'm having for help.
According to the documentation, I configured the subfolder in a session.
The manager opens the correct user subfolder, but when uploading, it is uploading to the root folder and not to the subfolder.

See my session var_dump: (PHP create subfolders according to year/month/day/post-ID)

array (1) {["RF"] => array (7) {["verify"] => string (21) "RESPONSIVEfilemanager" ["language"] => string (5) "en_US" ["subfolder"] => string (13) "2017/10/17/1/" ["view_type"] => int (0) ["sort_by"] => string (4) "name" true) ["filter"] => string (0) ""}}

The most curious thing is, yesterday, when I included the filemanager in the project, it worked normal. But today when trying to do the same thing (upload files with diferent users), the file is uploading to the root folder (/uploads) and not to the subfolder (/uploads/2017/10/17/1/)

Can you help me?

Apparently the session is correct.

**Comment by trippo** [comment]
You are right the new upload method not consider subfolder, i'm releasing a fix

**Comment by trippo** [comment]
Fixed in nei release 9.12.1
