### ISSUE TITLE
multiple add files

### ISSUE THREAD

**Issue by Grinyaha** [trippo/ResponsiveFilemanager#401]
Hi!
in dialog.php need add multiple, like this
<input type="file" name="files[]" multiple>
else not added more files for one time.

**Comment by trippo** [comment]
?

**Comment by Grinyaha** [comment]
`<input type="file" name="files[]" multiple="multiple">`

**Comment by Grinyaha** [comment]
string 494 in dialog.php

**Comment by trippo** [comment]
fixed
