### ISSUE TITLE
Cannot upload image

### ISSUE THREAD

**Issue by bossby** [trippo/ResponsiveFilemanager#402]
I'm trying to upload but i get this error .

`<br />
<b>Warning</b>:  mime_content_type(): open_basedir restriction in effect. File(/var/www/html/tes_loecari_com/tmp/phpat0AZf) is not within the allowed path(s): (/var/www/html/trial:/var/tmp/) in <b>/var/www/html/trial/assets/filemanager/upload.php</b> on line <b>95</b><br />
<br />
<b>Warning</b>:  mime_content_type(/var/www/html/tes_loecari_com/tmp/phpat0AZf): failed to open stream: Operation not permitted in <b>/var/www/html/trial/assets/filemanager/upload.php</b> on line <b>95</b><br />
<br />
<b>Warning</b>:  filesize(): open_basedir restriction in effect. File(/var/www/html/tes_loecari_com/tmp/phpat0AZf) is not within the allowed path(s): (/var/www/html/trial:/var/tmp/) in <b>/var/www/html/trial/assets/filemanager/UploadHandler.php</b> on line <b>296</b><br />
{"files":[{"name":"test.jpeg","size":141268,"type":"image\/jpeg","error":"File is too small"}]}`

I'm bit confuse, because my website folder is in `trial` but why there is `tes_loecari_com` in there error log. sorry for my bad english

**Comment by trippo** [comment]
The problem is the tmp folder configuration in your server see this: https://stackoverflow.com/questions/1846882/open-basedir-restriction-in-effect-file-is-not-within-the-allowed-paths
