### ISSUE TITLE
9.12.1: no thumbs in local server with windows os

### ISSUE THREAD

**Issue by labby** [trippo/ResponsiveFilemanager#406]
First of all: online (linux webserver) it works :-), 
but when I use a local usbwebserver on windows desktop thumbs were not created in the filemanager's thumbs folder with a weired message:
`Fatal error: Uncaught Error: Call to undefined function mime_content_type() in D:\Develope\Entwicklung\LEPTON_SVN\root\test\modules\lib_r_filemanager\filemanager\include\php_image_magician.php:2723 Stack trace: #0 D:\Develope\Entwicklung\LEPTON_SVN\root\test\modules\lib_r_filemanager\filemanager\include\php_image_magician.php(230): imageLib->openImage('../../..//media...') #1 D:\Develope\Entwicklung\LEPTON_SVN\root\test\modules\lib_r_filemanager\filemanager\include\utils.php(320): imageLib->__construct('../../..//media...') #2 D:\Develope\Entwicklung\LEPTON_SVN\root\test\modules\lib_r_filemanager\filemanager\dialog.php(1021): create_img('../../..//media...', '../thumbs/DSCF0...', 122, 91, 'crop', Array) #3 {main} thrown in D:\Develope\Entwicklung\LEPTON_SVN\root\test\modules\lib_r_filemanager\filemanager\include\php_image_magician.php on line 2723`

The funny thing is, if I copy a thumb to the thumbs_folder everything works fine. even if I rename the image in the media folder or delete it, it well be renamed or deleted in the thumbs_folder. 
I assume it is a "path issue" when creating thumbs ...

**Comment by trippo** [comment]
I think you must set your php to have mime_content_type
http://php.net/manual/en/function.mime-content-type.php
Very strange your error.

**Comment by labby** [comment]
Yepp, you are right.
Searching php.net I found this
[http://php.net/manual/en/fileinfo.installation.php](url)

> Windows users: just edit php.ini and uncomment this line:

> extension=php_fileinfo.dll

> Remember to restart Apache for new php.ini to take effect.

Don't knwo if it is the same with windows IIS, but it helps me on my local usbwebserver.
Hope this will also help others :-)
