### ISSUE TITLE
custome config in folder do not affect permissions

### ISSUE THREAD

**Issue by TomTheRock** [trippo/ResponsiveFilemanager#407]
Hi Alberto,

i just updated to your new Version 9.12.1, and updated my old custome config.php in subfolder, but it seems the additional config.php has no effect. I can still create folders e.g.

PHP 5.6

My Folder:
/upload/_filemanager/

My additional config: /upload/_filemanager/config.php
`return array(
		'create_folders'                          => false
		);`

I also Debug your dialog.php Code on Line 133:

You use: 
`$config = $config + $configTemp;`
My fix worked on a short test:
`$config = array_merge($config,$configTemp);`

Please give me Feedback about this if you have the same Problem, maybe it depends on which PHP Version or Hoster you are!?

Best Regards
Tom

**Comment by trippo** [comment]
You are right i'll change in next version
