### ISSUE TITLE
S3 directories

### ISSUE THREAD

**Issue by rathinam90** [trippo/ResponsiveFilemanager#413]
I want to integrate aws s3 Bucket on the file explorer.
Which means listing all directories and files of s3 in the explorer and download required files.
Is it possible ? If it is yes, Please assist me how ??

**Comment by trippo** [comment]
It's a difficult operation because rfm it's not strutture to easy add new file mode, when i have time i want rewrite all code

**Comment by ojha007** [comment]
any update about integration with s3
