### ISSUE TITLE
tiff upload fixed_image_creation

### ISSUE THREAD

**Issue by shimbala** [trippo/ResponsiveFilemanager#414]
Hi, 

When uploading .tiff fixed image thumbnail isn't created. Other image types, works as expected (.png, .jpg).
I'm on wamp 3.0.6 using gd library.

Is there a way, with your plugin? I'm using latest version - 9.12.1

Cheers, Erik

**Comment by trippo** [comment]
The image preview and thumbnail creation is not compatible with tiff image please put tiff extension on files list on config.php to see the default file thumb

**Comment by shimbala** [comment]
OK, thanks
