### ISSUE TITLE
Upload image not working when height > width

### ISSUE THREAD

**Issue by holygon** [trippo/ResponsiveFilemanager#416]
I want to upload a image width height > width. But it didn't work.

**Comment by trippo** [comment]
On my test work fine please share your example

**Comment by holygon** [comment]
I try upload a image with width: 400px and height: 500px. 

Warning: imagecreatetruecolor() expects parameter 2 to be long, string given in <b>C:\xampp\htdocs\daiviettin\application\views\auth\js\filemanager\include\php_image_magician.php</b> on line <b>361</b><br /> <br /> <b>Warning</b>: imagealphablending() expects parameter 1 to be resource, null given in
...
Not enought Memory (@C:\xampp\htdocs\daiviettin\application\views\auth\js\filemanager\upload.php#241)

**Comment by trippo** [comment]
Do you have this error also on online demo page?
