### ISSUE TITLE
image_check_memory_usage incorrectly fails

### ISSUE THREAD

**Issue by darrena092** [trippo/ResponsiveFilemanager#417]
There's an issue with image_check_memory_usage in utils.php in a couple of cases:

- If 'memory_limit' is set to -1 (unlimited), the memory limit evaluation will return an incorrect value and then false is returned incorrectly.

- If 'memory_limit' uses any other shorthand notation than 'M' (for example, we could say '1G'), then it will also return false incorrectly.

Happy to submit a PR if needed/wanted.

**Comment by trippo** [comment]
Thanks please send me a PR
