### ISSUE TITLE
Set subfolder as root folder

### ISSUE THREAD

**Issue by Keenjix** [trippo/ResponsiveFilemanager#420]
Hi, I'm looking for a way to set a subfolder as root. The script is amazing but the documentation about this part is really not useful :/
I have actually 3 folders {picture, movie, document} inside the "medias" folder.

- Medias
| -- picture
| -- movie
| -- document

On my website, there is 3 links for each folder, and it opens RF for each folder by this :

`<iframe width="100%" height="600px" frameborder="0" src="../libs/filemanager/dialog.php?type=0&amp;fldr=/medias/picture (or movie ; document)/"></iframe>` (that part work)

I wish that : When someone is inside the folder, he CAN'T go back to the parent folder, actually I tried everything possible, with the $_SESSION['RF']['subfolder'], with the config.php file in each folder, nothing works, I always have the parent link displayed. (see the attached file)

![](https://uploads.disquscdn.com/images/669ca6151393a320c23dca63447851195bacda3518d9eb3e5d30c19e0bf922c9.png)

Please help me clearly, step by step, I tried to solve this many month ago and finally gave up until this day, I can't go far.. :(
Thx

**Comment by Keenjix** [comment]
Please :(

**Comment by trippo** [comment]
You can set the variable like
 $_SESSION['RF']['subfolder']= "medias/picture"

before click the link...
In your case I think do you want to pass this param in the link so you can edit dialog.php to read a subfolder GET param and set  $_SESSION['RF']['subfolder']

**Comment by Keenjix** [comment]
There is no change. I'm actually in the folder "medias/picture"
I have my $_SESSION['RF']['subfolder'] set to "medias/picture"

But I still have the "Back" link displayed in RF. (Like on my screen in the first post)

**Comment by trippo** [comment]
I think you have different sessions I tried now on my localhost and work fine.
Try to set manually on dialog.php 
$_SESSION['RF']["subfolder"] = "medias/picture/";
with the last /

**Comment by Keenjix** [comment]
I just did it, and it display me the root without any possibility to go in a folder, not the subfolder that I want it to become root.

**Comment by trippo** [comment]
are you sure do you have session compatibility? try to print session var or try to print $rfm_subfolder after line 107 of dialog.php

**Comment by Keenjix** [comment]
$rfm_subfolder is always empty, var_dump, or print, it's always empty, doesn't matter if $_SESSION['RF']["subfolder"] is empty or not, no difference.

And I never had problem with sessions except the subfolder one :/

**Comment by trippo** [comment]
do you have last version of rfm? can you send me a ftp access?

**Comment by Keenjix** [comment]
I finally found what was the problem. When I call RF stand-alone, I set the folder to open with "fldr="

`<iframe width="100%" height="600px" frameborder="0" src="../libs/filemanager/dialog.php?type=0&amp;fldr=medias/picture/"></iframe>`

And before that I call $_SESSION['RF']['subfolder'] = "medias/picture/";
The problem is "fldr", I have to set it to root like fldr=/ and then $_SESSION['RF']['subfolder'] do the job to "root" medias/picture/

I don't know if you understand. But anyway, finally found how to fix it. I made a clean install in localhost like you mentionned it, and it helped me. So thank you, I have no problem anymore :)

**Comment by andsigno82** [comment]
sorry, but i have same problem and setting 
`$_SESSION['RF']['subfolder'] = "sub1/sub2/"` 
before iframe call, didn't do the trick...
