### ISSUE TITLE
Uploading .svg gets converted to .html

### ISSUE THREAD

**Issue by sushantaryal** [trippo/ResponsiveFilemanager#436]
When i try to upload the image with .svg extension it gets converted to .html
Here is the screenshot.
![before](https://user-images.githubusercontent.com/8115655/35914766-90203bf6-0c2c-11e8-8f45-7e50b45c1228.jpg)
![after](https://user-images.githubusercontent.com/8115655/35914771-97b5b8be-0c2c-11e8-9e29-f2d578b9281a.jpg)

**Comment by WebVeteran** [comment]
I have two pull requests to make file name extension renaming an option in the config.

**Comment by trippo** [comment]
I will include this config on config.php on new release
