### ISSUE TITLE
Can't upload file: PHP Warning chmod(): No such file or directory

### ISSUE THREAD

**Issue by fatonio** [trippo/ResponsiveFilemanager#445]
Hello, 

I use ubuntu 17.10 with valet as a local server, I can't upload/create file but can create / delete folders and rename / delete files...  I get error in **nging-error.log**. 

`PHP message: PHP Warning:  chmod(): No such file or directory in /media/user/data/projects/awesome/vendor/filemanager/UploadHandler.php on line 1407" while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /vendor/filemanager/upload.php HTTP/1.1", upstream: "fastcgi://unix:/home/user/.valet/valet.sock:", host: "awesome.test", referrer: "http://awesome.test/vendor/filemanager/dialog.php?editor=tinymce&type=1&lang=en_EN&popup=0&crossdomain=0&field_id=image&relative_url=1&akey=key&fldr=&5ac5fd3f9bedd&1522924890338"`

How to fix it?

**Comment by trini-tA** [comment]
Hi,

Have you change current_path and thumbs_base_path ? 
if you don't use relatif path, upload not function !
