### ISSUE TITLE
upload csv renamed to txt

### ISSUE THREAD

**Issue by shimbala** [trippo/ResponsiveFilemanager#446]
Hi

If I upload .csv file, plugin automatically adds .txt extension to filename.
Example file.csv -> file.csv.txt

I there workaround?

Using version 9.12.2

Cheers, Erik

**Comment by WebVeteran** [comment]
Temporary workaround: https://github.com/trippo/ResponsiveFilemanager/issues/436

**Comment by mikaykun** [comment]
@trippo If this is fixed in #436 please close the issue.

**Comment by trippo** [comment]
In last version you can disable mime check in the config.php without #436
