### ISSUE TITLE
utf-8 filename & foldername support

### ISSUE THREAD

**Issue by gptforjoomla** [trippo/ResponsiveFilemanager#45]
ResponsiveFilemanager do not support utf-8 filename & foldername.

**Comment by miladghiravani** [comment]
In new version I have this problem. Please help me. Thx.

**Comment by miladghiravani** [comment]
I have this problem on windows with xampp, when upload on linux server, problem solved!! ([this](http://www.hamcodi.ir/qa/questions/1749/%D8%AA%D8%BA%DB%8C%DB%8C%D8%B1-%D9%86%D8%A7%D9%85-%D9%81%D8%A7%DB%8C%D9%84-%D8%A8%D8%B5%D9%88%D8%B1%D8%AA-%DB%8C%D9%88%D9%86%DB%8C%DA%A9%D8%AF-%D8%AF%D8%B1-php))
But why occurred this on windows?
