### ISSUE TITLE
error on upload with relative_image_creation = true: SyntaxError: Unexpected token < in JSON at position 0 

### ISSUE THREAD

**Issue by srghma** [trippo/ResponsiveFilemanager#456]
/filemanager/upload.php response 

```
<br />
<b>Warning</b>:  A non-numeric value encountered in <b>/var/www/html/filemanager/include/utils.php</b> on line <b>713</b><br />
<br />
<b>Warning</b>:  A non-numeric value encountered in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>832</b><br />
<br />
<b>Warning</b>:  Division by zero in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>832</b><br />
<br />
<b>Warning</b>:  A non-numeric value encountered in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>555</b><br />
<br />
<b>Warning</b>:  imagecreatetruecolor() expects parameter 2 to be integer, string given in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>491</b><br />
<br />
<b>Warning</b>:  imagecolorallocate() expects parameter 1 to be resource, null given in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>466</b><br />
<br />
<b>Warning</b>:  imagefilledrectangle() expects parameter 1 to be resource, null given in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>467</b><br />
<br />
<b>Warning</b>:  imagecopyresampled() expects parameter 1 to be resource, null given in <b>/var/www/html/filemanager/include/php_image_magician.php</b> on line <b>493</b><br />
{"files":[{"name":"2 (5).jpg","size":155835,"type":"image\/jpeg","path":"\/var\/www\/html\/filemanager\/..\/source\/2 (5).jpg","url":"\/filemanager_source\/2%20%285%29.jpg","deleteUrl":"https:\/\/rails-stage-new.XXXXX.com\/filemanager\/upload.php?file=2%20%285%29.jpg","deleteType":"DELETE"}]}
```

![screencapture-rails-stage-new-vdare-admin-publications-new-2018-04-30-12_02_53](https://user-images.githubusercontent.com/7573215/39420777-b012ce1a-4c6e-11e8-9719-5d4769a0fb98.png)

full config https://pastebin.com/raw/UAtPamz3

How to reproduce: `'relative_image_creation'                 => true,`

Dockerfile this container created with:
```
FROM php:7.2.3-apache

RUN apt-get update && \
    apt-get install unzip && \
    apt-get clean

# install php-extensions (from https://hub.docker.com/_/php/)
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

# install filemanager
ENV FILEMANAGER_DOWNLOAD="https://github.com/trippo/ResponsiveFilemanager/releases/download/v9.12.2/responsive_filemanager.zip"

RUN curl -L -O "${FILEMANAGER_DOWNLOAD}" && \
    unzip *.zip && \
    rm -f *.zip

RUN mkdir -p source && \
    chown -R www-data:www-data . && \
    chmod -R 777 source

```

**Comment by pioneersingh321** [comment]
Sir i am also facing the same issue .. when we are cropping image in multiply sizes  .. images are getting uploaded on folders ... i think its error is coming  with Json format when we are cropping image in multiply sizes

**Comment by appzstory** [comment]
v.9.14.0
filemanager/upload.php
line 128: change upload_handler -> $upload_handler

I hope it can help you.

**Comment by trippo** [comment]
Thanks

**Comment by duongnam99** [comment]
seem like this error is very "well know", but still no answer.

**Comment by webtimi** [comment]
UploadHandler.php change line: 1431 
$uploaded_bytes = $this->fix_integer_overflow((int)(isset($content_range[1]) ? $content_range[1]: 1));

php 7.4 not null array

**Comment by kyobul** [comment]
> UploadHandler.php change line: 1431
> $uploaded_bytes = $this->fix_integer_overflow((int)(isset($content_range[1]) ? $content_range[1]: 1));
> 
> php 7.4 not null array

+ line in 496 in the same file

**Comment by seyitahmettanriver** [comment]
> UploadHandler.php change line: 1431
> $uploaded_bytes = $this->fix_integer_overflow((int)(isset($content_range[1]) ? $content_range[1]: 1));
> 
> php 7.4 not null array

**Thanks.**

Change all the 
`$uploaded_bytes = $this->fix_integer_overflow((int)$content_range[1]);`
 places in the "**UploadHandler.php**" folder to  
`$uploaded_bytes = $this->fix_integer_overflow((int)(isset($content_range[1]) ? $content_range[1]: 1));`
 _(There are 2 such lines in total.)_

**Comment by nikzad-avasam** [comment]
> > UploadHandler.php change line: 1431
> > $uploaded_bytes = $this->fix_integer_overflow((int)(isset($content_range[1]) ? $content_range[1]: 1));
> > php 7.4 not null array
> 
> **Thanks.**
> 
> Change all the
> `$uploaded_bytes = $this->fix_integer_overflow((int)$content_range[1]);`
> places in the "**UploadHandler.php**" folder to
> `$uploaded_bytes = $this->fix_integer_overflow((int)(isset($content_range[1]) ? $content_range[1]: 1));`
> _(There are 2 such lines in total.)_

I did the same, but the problem was not solved ...
