### ISSUE TITLE
Malware/Virus Scan on Upload

### ISSUE THREAD

**Issue by BiffJingles** [trippo/ResponsiveFilemanager#457]
Anyone had success on implementing a virus/malware scan on uploading of files?  Looking to see where the best place to implement this is.  Any help would be appreciated.

Thanks.

**Comment by sashaptrw** [comment]
Are you serious?

**Comment by trippo** [comment]
You can do it on upload.php file

**Comment by mikaykun** [comment]
@sashaptrw You can use the API from Virus Total (https://developers.virustotal.com/v2.0/)

**Comment by sashaptrw** [comment]
Where's the fun in that ;)

**Comment by sashaptrw** [comment]
@mikaykun Where's the fun in that? ;)
