### ISSUE TITLE
This following code make the selected photo can not inserted into CKEditor

### ISSUE THREAD

**Issue by codesonteen** [trippo/ResponsiveFilemanager#461]
On file include.js

`else {
            var a = jQuery("#editor").val();
            if ("ckeditor" == a) {
                var r = j("CKEditorFuncNum");
                window.opener.CKEDITOR.tools.callFunction(r, e), window.close()
            } else parent.tinymce.majorVersion < 4 ? (parent.tinymce.activeEditor.windowManager.params.setUrl(e), parent.tinymce.activeEditor.windowManager.close(parent.tinymce.activeEditor.windowManager.params.mce_window_id)) : (parent.tinymce.activeEditor.windowManager.getParams().setUrl(e), parent.tinymce.activeEditor.windowManager.close())
        }`

After I investigated, $("editor#).val(); will return a null instance which caused the IF-condition ("ckeditor" == a) after that always be false and lead to error exception.

After I remove the IF-condition and leave those expressions in the condition remain, The function works.

**Comment by trippo** [comment]
You must pass &editor=ckeditor in the url of ckeditor init like documentation

**Comment by codesonteen** [comment]
I have done it. 

But there is an issue when having multiple CKEditor instances (multiple id).

I then modify the code on those lines to the code I attached below and it works

`
let urlQueryString = window.location.search;
let searchResult = urlQueryString.search('ckeditor');
if(searchResult > 0){
`
