### ISSUE TITLE
Error - The folder is already existing

### ISSUE THREAD

**Issue by caophihung94** [trippo/ResponsiveFilemanager#463]
I'm using ResponsiveFilemanager 9.13.0. When I try to create a new folder, the error appears: "The folder is already existing". (This folder has never been created before.)

![2018-06-04_104310](https://user-images.githubusercontent.com/15188241/40897423-3e8c3186-67e5-11e8-8cd6-a047ab9f8b68.PNG)

**Comment by trippo** [comment]
On my localhost and site demo work fine. Please try to empty cache

**Comment by Nak9009** [comment]
I’m same my problem. 
When create folder it not show folder. 
When refresh it show folder.

**Comment by trippo** [comment]
where can i see this error?

**Comment by trippo** [comment]
it's very strange can you test on my demo page at responsivefilemenager.com/demo.php

**Comment by merlin334** [comment]
To fix "The folder is already existing", find execute.php from filemanager folder and comment or delete line 160-162: 
// if(!$res){
	// response(trans('Rename_existing_folder').AddErrorLocation())->send();
// }

**Comment by mayrk** [comment]
I have the same message on the latest GitHub version.

If an existing Foldername (created and used in previous versions of RF) 
contains a "." e. g. as abbreviation from typical words, it is not possible
to create a folder inside. Upload of files in this folder however works ...

9.12.2 : Nothing happens
9.13.0/1 and master: "The folder is already existing"

It is also not possible to rename an old folder with a "." in it.

**Comment by trippo** [comment]
this because RFM not permit to insert folder names with . so you must rename old folders with .
