### ISSUE TITLE
Unable to create folders

### ISSUE THREAD

**Issue by mpryvkin** [trippo/ResponsiveFilemanager#466]
Using PHP 5.6.33, ResponsiveFilemanager 9.12.1.

My config file has the following line:

```
'current_path' => '../../',
```

When creating a folder, POST request is sent `filemanager/execute.php?action=create_folder` with the following parameters `name=test1&path=`. I get `Wrong extension` as a response.

I traced the error to the following line where `pathinfo("../../")` sets `extension` attribute which prevents folder creation, see below.

```
$info = pathinfo($path);
if (isset($info['extension']) && !(isset($_GET['action']) && $_GET['action']=='delete_folder') && !in_array(strtolower($info['extension']), $ext) && $_GET['action'] != 'create_file')
```

As I workaround I am using the code below.

```
$info = pathinfo($path);
if (isset($info['extension']) && !(isset($_GET['action']) && in_array($_GET['action'], array('create_folder', 'rename_folder', 'delete_folder'))) && !in_array(strtolower($info['extension']), $ext) && $_GET['action'] != 'create_file')
```

**Comment by trippo** [comment]
fixed on 9.13.1
