### ISSUE TITLE
Permission for Download Button ?

### ISSUE THREAD

**Issue by mayrk** [trippo/ResponsiveFilemanager#469]
Is it possible to include a permission for the "Download" button in the default release ?

I am testing RFM on our companys webserver to create a dataroom (like e.g. netfiles.de) with 
only VIEW permission for documents. I can set anything but the "Download" to false in the permissions section of config.php.

I implemented my modification in my installation in the config.php and dialog.php files.

Would be nice if i do not have to edit too much files when i use a newer release of RFM ... :-)

**Comment by mikaykun** [comment]
@mayrk Try to create a pull request

**Comment by mayrk** [comment]
Merged as #470. I close this issue. :-)
