### ISSUE TITLE
Renaming file twice fails with error

### ISSUE THREAD

**Issue by cdaveb** [trippo/ResponsiveFilemanager#484]
If you rename a file in the file manager, and then rename it again, it fails with an error "The file is already existing " referencing responsivefilemanager/9.13.1/execute.php#271

This appears to be possible to work around by closing the file manager and reopening it, but it should really be fixed so that a second rename doesn't fail.

I noticed this issue while testing 9.13.1 but it appears to also be a problem in the previous version we were using, which is 9.12.2.

**Comment by trippo** [comment]
thanks you can see this fix in the next version
