### ISSUE TITLE
Request for SSL license.php

### ISSUE THREAD

**Issue by timmetj** [trippo/ResponsiveFilemanager#489]
Hello,

Can you maybe add a SSL to your hosting? So the license (http://responsivefilemanager.com/license.php) can be SSL also. Else you get these mixed content notices. Or can it just be an internal image?

Greetings

**Comment by trippo** [comment]
You are right.. I change server and add a https certificate so you can change http to https in the javascript

**Comment by trippo** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=responsivefilemanager.com
