### ISSUE TITLE
Feature Request: Alt tags

### ISSUE THREAD

**Issue by visualvoice** [trippo/ResponsiveFilemanager#508]
Hello,
Could you add alt tag support for the TINYMCE plugin?

**Comment by trippo** [comment]
You can use 
<img width="53" alt="schermata 2018-11-05 alle 19 42 07" src="https://user-images.githubusercontent.com/497169/48019173-0c417c00-e133-11e8-9454-42249795ba21.png">

responsivefilemanager plugin to return alt tag on editor. Please see demo page.
