### ISSUE TITLE
Bug with standalone use in 9.13.4 ?

### ISSUE THREAD

**Issue by fredtempez** [trippo/ResponsiveFilemanager#509]
Hello
Using as a standalone file manager, when calling for a file, callback url return filename without relative path. 
Here is the call back code we use in our CMS : 
/**
 * Callback de RFM
 */
function responsive_filemanager_callback(fieldId) {
	$("#" + fieldId).trigger("change");
	$(".lity-close").trigger("click");
}
The issue is in 9.13.4 but not in 9.12.2 we had to use. 
Maybe there is a change we didn’t see ?
Thanks for you help.

**Comment by trippo** [comment]
Thank's to reporting I'll fix in next version in one day
