### ISSUE TITLE
Using FancyBox Relative_URL=1 Not working

### ISSUE THREAD

**Issue by smuglet** [trippo/ResponsiveFilemanager#514]
I have the latest version 9.13.4 and I set relative_url=1 as a GET param to dialog.php as in the examples but i am only receiving the filename in the associated input field.  I can't see anything wrong with code.  If I set to 0 the absolute URL comes through.

Help.

**Comment by trippo** [comment]
Yes it will correct in next version

**Comment by smuglet** [comment]
Great thanks... how often do new versions roll out?
