### ISSUE TITLE
Duplicate file does not work

### ISSUE THREAD

**Issue by trident-ms** [trippo/ResponsiveFilemanager#520]
It seems to me that in **execute.php** the function **duplicate_file** receives just the path of the folder of the file to duplicate, but not the complete path.

It cannot work. The **copy** command in **utils.php-duplicate_file** fails.

Am I wrong??

**Comment by slimtim** [comment]
I confirmed that the duplicate file feature does not work. When I right click a file, select Duplicate, and then click OK I get these PHP notices:

```
Notice: Undefined index: path in filemanager/execute.php on line 11
Notice: Undefined index: path in filemanager/execute.php on line 32
Notice: Undefined index: path in filemanager/execute.php on line 92
Notice: Undefined index: extension in filemanager/include/utils.php on line 246
The file is already existing (@filemanager/execute.php#296)
```

The `name` parameter is being submitted to execute.php but the `path` parameter is not.

**Comment by trippo** [comment]
fixed on next release
