### ISSUE TITLE
PHP (Fatal) errors using FTP configuration

### ISSUE THREAD

**Issue by Giampieroo** [trippo/ResponsiveFilemanager#521]
Version 9.14.0 using FTP configuration

I found a few things, hope someone can help fix these.

- Can't delete files:
PHP Fatal error:  Cannot redeclare class FtpClient\FtpClient in /home/..etcetera../filemanager/include/FtpClient.php on line 48

- When renaming a file:
PHP Warning:  ftp_rename(): //thumbs/stockfotos xxxxxxx.pdf: No such file or directory in /home/..etcetera../filemanager/include/FtpWrapper.php on line 85

- When creating a new folder modal says it already exits. On refresh the folder appears. No PHP error.

- Duplicating a file doesn't work and gives this load of PHP warnings:
PHP Notice:  Undefined index: path in /..xxxxx../filemanager/execute.php on line 12
PHP Notice:  Undefined index: extension in /..xxxxx../filemanager/include/utils.php on line 258
PHP Warning:  ftp_get(): //bestanden/: Not a regular file in /..xxxxx../filemanager/include/FtpWrapper.php on line 85
PHP Warning:  ftp_put(1543435915phi-phi-island - copy.): failed to open stream: Bestand of map bestaat niet in /..xxxxx../filemanager/include/FtpWrapper.php on line 85
PHP Warning:  unlink(1543435915phi-phi-island - copy.): Bestand of map bestaat niet in /..xxxxx../filemanager/include/utils.php on line 264
PHP Notice:  Undefined index: extension in /..xxxxx../filemanager/include/utils.php on line 258
PHP Warning:  ftp_get(): //thumbs/: Not a regular file in /..xxxxx../filemanager/include/FtpWrapper.php on line 85
PHP Warning:  ftp_put(1543435915phi-phi-island - copy.): failed to open stream: Bestand of map bestaat niet in /..xxxxx../filemanager/include/FtpWrapper.php on line 85
PHP Warning:  unlink(1543435915phi-phi-island - copy.): Bestand of map bestaat niet in /..xxxxx../filemanager/include/utils.php on line 264

- Image info: dimensions not displayed and html-tags
<img width="214" alt="afbeelding" src="https://user-images.githubusercontent.com/34095470/49180242-6d382a80-f354-11e8-9c79-31734708f3fa.png">

**Comment by SergiOnGit** [comment]
Can't delete files:
PHP Fatal error: Cannot redeclare class FtpClient\FtpClient in /home/..etcetera../filemanager/include/FtpClient.php on line 48

Same with me. Hope it will be fixed soon.
