### ISSUE TITLE
Uploading picture bigger than chunk size 2mb

### ISSUE THREAD

**Issue by bboy-space** [trippo/ResponsiveFilemanager#525]
If I try to upload a picture requiring many chunk uploads (~2.10MB) , it fails even if the mime type is ok. 
I took that picture (~6MB) and reduce it down to 1.5MB, and the upload worked so it doesn't come from the picture itself.
I thought it was an upload limitation in Apache so I increased it but it works in another APP running on the same server

I finally digged into the code and found that it fails from the second Ajax (and all other after) in the file UploadHandler.php  line 383  when trying to do : 

`if (preg_match($this->options['image_file_types'], $file->name) && function_exists('exif_imagetype') && !@exif_imagetype($uploaded_file)) {`

Indeed, i don't know why but the exif_imagetype function return false from the second chunk. 
I tried to remove this test and my picture was finally successfully uploaded.

Thanks for feedback on this

**Comment by d0p3fish** [comment]
The validation starts, but the image isn't completely uploaded .
This is a problem with the chunked file upload.

"exif_imagetype will emit an E_NOTICE
 * and return <b>FALSE</b> if it is unable to read enough bytes from the file to
 * determine the image type."

Hotfix for now: Disable the chunked file upload in UploadHandler.php
'readfile_chunk_size' => 2 * 1024 * 1024, // 10 MiB
->
'readfile_chunk_size' => 0

**Comment by bboy-space** [comment]
I appreciate your feedback.
As you suggested, I set 'readfile_chunk_size' => 0 but now it returns me the error  "Filetype not allowed"

The image is a classic JPG picture of 5MB (attached to my message)
![test](https://user-images.githubusercontent.com/5296748/50222707-5dcb6080-0399-11e9-8a09-38e190f412e2.jpg)

My APP is a personal local project so no need mega security, I'm the only user. 
I just want to be able to upload any picture I want without it fails. 
**Which workaround should i do ?**

Thanks

**Comment by d0p3fish** [comment]
Hi @bboy-space ,

take a look at the commit I referenced 1cff9a4

For your local project without "mega security" ;) you can remove or comment out these lines and it should work.

**Comment by bboy-space** [comment]
Hi @d0p3fish 
Thanks for your time.
Doing this, I confirm the upload is working (I have my full 5Mb "test.jpg" picture uploaded with no corruption in the source folder ) **BUT**  it fails creating the thumbnail. 

I have nothing in the thumb folder, and the GUI returns an error (screenshot attached)
`SyntaxError: Unexpected token < in JSON at position 0`

![image](https://user-images.githubusercontent.com/5296748/50339318-7d889300-0517-11e9-8e43-e14322cb4f40.png)

**Comment by d0p3fish** [comment]
Hi @bboy-space ,

you can revert your changes in UploadHandler.

But in
include.js
search for
maxChunkSize: 2097152
and set it to
maxChunkSize: 0

@trippo The validate() method in the UploadHandler is called for every uploaded file part.

for the first uploaded chunk, exif_imagetype is receiving the first bytes of the file, and returns 2 (jpeg) or something.
but for the remaining chunks its returning false and the upload fails.

**Comment by bboy-space** [comment]
@d0p3fish, Thanks again for replying.

I made the changes you suggested, but i'm sorry to say it still doesn't work 
I had to clean up the cache for the JS file to be sure : here again a screenshot with chrome console showing the maxChunkSize attribute

![image](https://user-images.githubusercontent.com/5296748/50347623-7d4bc000-0536-11e9-98b2-c890c167e9d6.png)

**Comment by d0p3fish** [comment]
Hi,

take a look at the (google chrome?) developer tools. After uploading, the response from upload.php is not json.
in the response you will see the "real" error message.

**Comment by bboy-space** [comment]
Hi @d0p3fish ,

First of all, Happy new year :)
I have new elements for the investigation.

Looking at the real error in developer tools, from the Ajax call it says : 
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in E:\projects\backoffice\third_party\filemanager\UploadHandler.php on line 570`  (cf screenshot)

![image](https://user-images.githubusercontent.com/5296748/50586389-7cd9f000-0e79-11e9-8671-0e1d129bf356.png)

Current code: 
- comment enabled on @exif_imagetype AND property MaxChunkSize = 0

Investigation:
- First workaround, I added `ini_set('memory_limit', '2G');` at the beginning of UploadHandler.php file
- I tried again => upload success but still not creating thumbnail
- Tried to set back JS MaxChunkSize to initial value => same (works without thumbnail)
- Tried to remove comments on @exif_imagetype => Upload error Filetype not allowed

**Comment by bboy-space** [comment]
Update : After lots of debug I found the combo that works 

- UploadHandler.php

 => Keep the comments around @exif_imagetype
`        /*
        if (preg_match($this->options['image_file_types'], $file->name) && function_exists('exif_imagetype') && !@exif_imagetype($uploaded_file)) {
            $file->error = $this->get_error_message('accept_file_types');
            return false;
        }
        */`

- UploadHandler.php

 => readfile_chunk_size => set back to it default as default value => 2 * 1024 * 1024. If set to 0, the code skip uploadEnd function

- include.js

 => maxChunkSize => set back to it default value => 2097152

Now everything is working with my 5Mb picture.
Thanks for help

**Comment by trippo** [comment]
So what's the solutions?

**Comment by bboy-space** [comment]
> So what's the solutions?

hello @trippo ,
As said, what is working for me is from the original code, only comment this part in UploadHandler.php

`
        if (preg_match($this->options['image_file_types'], $file->name) && function_exists('exif_imagetype') && !@exif_imagetype($uploaded_file)) {
            $file->error = $this->get_error_message('accept_file_types');
            return false;
        }
        
`

**Comment by d0p3fish** [comment]
> So what's the solutions?

The validation should be done at the end of the file upload, not on every chunk.
https://github.com/trippo/ResponsiveFilemanager/issues/525#issuecomment-449398833

**Comment by noyearzero** [comment]
I can confirm this change removes the error.  

Maybe it would be best to do validate at both the first chunk and after the file is assembled from all the chunks.  It seems like validate is being called on the first chunk and is passing.  I'm guessing because the meta data is at the beginning of the file.  It recommend checking it on the first chunk so that you don't have to upload a whole bunch of chunks just to find out that the whole thing is going to fail.

Also, when one or more chunks do fail, it might be nice to delete the file it started.  If you start a file and it fails, there is a partial file left there and it makes subsequent upload attempts append a number.  In the below image you should be able to see the bottom of the bottles.

![3_bottlesx](https://user-images.githubusercontent.com/2496224/53366563-e7eff200-3911-11e9-8214-7ed7dac9c85a.jpg)

**Comment by trippo** [comment]
I think this issue was closed
