### ISSUE TITLE
Delete throws error with ftp

### ISSUE THREAD

**Issue by SergiOnGit** [trippo/ResponsiveFilemanager#530]
error: **PHP Fatal error: Cannot redeclare class FtpClient\FtpClient in /home/..etcetera../filemanager/include/FtpClient.php on line 48**

Also i have problem with live development. File uploading works fine in my local machine but not on hosting. When i try to upload image it throws json error **"SyntaxError: Unexpected token o in JSON at position 1"** and in network api route "upload.php" prints text "forbidden".

Can enyone help me to fix this issues? I believe i am not the only one with issues.

**Comment by vankeung** [comment]
In \filemanager\upload.php
	
deleteFile($path,$path_thumb,$config);

replace to below code

> switch($_GET['action'])
	`{`
		'case 'delete_file':'
			'deleteFile($ftp,$path,$path_thumb,$config);'


In   \filemanager\include\utils.php

**Add $ftp into the deleteFile parameter**
`function deleteFile($ftp,$path,$path_thumb,$config){`
`	if ($config['delete_files']){`
**Hide below code**		
`//$ftp = ftp_con($config);`
