### ISSUE TITLE
[BUG] Filename with Ampersand!

### ISSUE THREAD

**Issue by markmorris** [trippo/ResponsiveFilemanager#534]
Uploaded a bunch of tracks. Ones that contained Ampersands did the below.

![screenshot from 2019-01-28 12-47-03](https://user-images.githubusercontent.com/7857906/51837304-ecb58c00-22fa-11e9-8b69-186311ffca6b.png)

Any suggestions.

**Comment by trippo** [comment]
please activate transliteration in config
