### ISSUE TITLE
Found issue: 'The folder is already existing', when creating folder via FTP

### ISSUE THREAD

**Issue by linaseniorwebdev** [trippo/ResponsiveFilemanager#540]
When creating folder on FTP, the directory is created, but receive message 'The folder is already existing'.
This is because of 'create_folder' function in '\filemanager\include\utils.php', line 560.

function create_folder($path = null, $path_thumbs = null, $ftp = null, $config = null)
{
    if ($ftp) {
        $ftp->mkdir($path);
        $ftp->mkdir($path_thumbs);
    } else {
...

I solved such issue by adding some lines like:

if ($ftp) {
        $result_path = $result_thumb = false;
        $result_path = $ftp->mkdir($path);
        $result_thumb = $ftp->mkdir($path_thumbs);
        if ($result_thumb == false || $result_path == false)
            return false;
        return true;
    } else {
...

$ftp->mkdir returns path if successful, otherwise false.
And 'create_folder' function must return a value.
If not, you will always see a message "The folder is already existing"
Hope this could help others.

**Comment by trippo** [comment]
thanks a lot for this
