### ISSUE TITLE
Found issue: Cannot delete file(s) via FTP

### ISSUE THREAD

**Issue by linaseniorwebdev** [trippo/ResponsiveFilemanager#541]
Some missing parts are in this source.

There are several spots to modify.

1) ./filemanager/execute.php
    Line 108:
        deleteFile($path, $path_thumb, $config); => deleteFile($path, $path_thumb, $ftp, $config);
    Line 114:
        deleteFile($p, $paths_thumb[$key], $config); => deleteFile($p, $paths_thumb[$key], $ftp, $config);

2) ./filemanager/include/utils.php
    Line 150:
        function deleteFile($path, $path_thumb, $config) => function deleteFile($path, $path_thumb, $ftp = null, $config = null)

This change made it works. Hope this will be help of you.

**Comment by trippo** [comment]
this is wrong because ftp it's initialized on deletefile function $ftp = ftp_con($config);

**Comment by linaseniorwebdev** [comment]
Test by yourself.

**Comment by trippo** [comment]
I think there is another type of error, did you try to find because the initial value $ftp = ftp_con($config); don't work?

**Comment by linaseniorwebdev** [comment]
Yeah, it dies on the line 387 of 'utils.php'
I debugged my myself line by line.
Finally got to 'function ftp_con($config)'
There, it goes to 'catch' clause and 'die()' as a result.
So on the interface, it looks that file is deleted. But it's not, then.
You can check by yourself, if you don't believe me.
Thank you for your reply.
