### ISSUE TITLE
Notice: Undefined index: thumbs_upload_dir in filemanager\dialog.php on line 111

### ISSUE THREAD

**Issue by cfconsultancy** [trippo/ResponsiveFilemanager#556]
Notice: Undefined index: thumbs_upload_dir in filemanager\dialog.php on line 111

is not defined in config.php

**Comment by trippo** [comment]
Yes but i updated config.php on release after first release:
https://github.com/trippo/ResponsiveFilemanager/blob/master/filemanager/config/config.php
