### ISSUE TITLE
relative_urls : false for image with tinymce 5

### ISSUE THREAD

**Issue by gtraxx** [trippo/ResponsiveFilemanager#566]
Hi, relative_urls: false no longer works with tinymce 5 for images : 
tinymce 4 : /media/Logo_rogne.png is ok
tinymce 5 : http://www.domain.tld/media/Logo_rogne.png

**Comment by futureweb** [comment]
@gtraxx - were you able to fix this as you closed the Bug yourself?
Got the same problem with TinyMCE 5 ... my "relative_urls : false" is simply ignored and I always get back the absolute URL ...
thx
