### ISSUE TITLE
Handling field_ids with brackets, for example: inputarray[image]

### ISSUE THREAD

**Issue by bavamont** [trippo/ResponsiveFilemanager#570]
Change line 391 in dialog.php from 
`<input type="hidden" id="field_id" value="<?php echo $field_id;?>" />`
to
`<input type="hidden" id="field_id" value="<?php echo str_replace(['[',']'],['\[','\]'], $field_id);?>" />`

Now you can pass a field_id with brackets.

**Comment by trippo** [comment]
I'll put in next release
