### ISSUE TITLE
Update jQuery File Upload plug-in to the latest version / Images stuck in "Processing" state

### ISSUE THREAD

**Issue by mpryvkin** [trippo/ResponsiveFilemanager#608]
There are multiple issues that the latest version solves, for example [this one](https://github.com/blueimp/jQuery-File-Upload/issues/3638) that results in uploaded images to be stuck at "Processing" state.

Currently file manager uses jQuery File Upload v9.22.0, latest version is v.10.28.0. 

Seems like the only change needed is to update version for `blueimp-file-upload` in `package.json`.

**Comment by bahmansh** [comment]
The latest version is 9.14, So where is 10.17 version?

**Comment by bahmansh** [comment]
The latest version is 9.14, So where is 10.17 version?

**Comment by mpryvkin** [comment]
@bahmansh I was mentioning jQuery Fileupload version, not ResponsiveFilemanager version, see [jQuery Fileupload release history](https://github.com/blueimp/jQuery-File-Upload/releases).

**Comment by trippo** [comment]
Please replace  http://blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js with  https://cdnjs.cloudflare.com/ajax/libs/blueimp-load-image/2.18.0/load-image.all.min.js on dialog.php

**Comment by gordon-matt** [comment]
@trippo Shouldn't you fix this and release a new version? And you should probably do the same for canvas-to-blob.min.js as well. Linking to files in GitHub is not the best idea.. Could you please update with CDN links and release a new one? Thanks
