### ISSUE TITLE
Folders/files are sorted using descending order by default

### ISSUE THREAD

**Issue by mpryvkin** [trippo/ResponsiveFilemanager#609]
Caused by the code below:

https://github.com/trippo/ResponsiveFilemanager/blob/428069746fabcef495b44d690bec20a05279a194/filemanager/dialog.php#L223-L225

Can be solved by setting `$_SESSION['RF']['descending'] = false`. Also this block can be moved, see example below:

```
if (isset($_GET["descending"])) {
    $descending = $_SESSION['RF']['descending'] = fix_get_params($_GET["descending"]) == 1;
} else {
    if (!isset($_SESSION['RF']['descending'])) {
        $_SESSION['RF']['descending'] = false;
    }

    $descending = $_SESSION['RF']['descending'];
}
```

**Comment by trippo** [comment]
thanks I'll put this code in next release
