### ISSUE TITLE
upload .jpg

### ISSUE THREAD

**Issue by modemanola** [trippo/ResponsiveFilemanager#611]
I'm having trouble uploading some .jpg files.
I also tried it on a demo site, and it won't upload either. Shows processing only.
Is there a solution?
![this one dont work](https://user-images.githubusercontent.com/46745254/81801256-67b4ad00-9514-11ea-8935-973f1128f69c.jpg)

**Comment by shimbala** [comment]
Hi, 
Open on photoshop and just SAVE FOR WEB...

Don't know why but that solved my problem.

**Comment by modemanola** [comment]
@shimbala thank you for your fast respond on this.. as a matter of fact, i have had some images that was not exported from photoshop and still won't upload, just hanging on processing.. 
Of course, solution is simple, but I wasn't able to find out why some of .jpg images won't upload :/

**Comment by RedwingNZ** [comment]
Probably related to #608 ...

**Comment by modemanola** [comment]
@RedwingNZ Thank you. That solves the problem 👍
