### ISSUE TITLE
Watermark not working filename uploaded has been transliterated

### ISSUE THREAD

**Issue by phulamnguyen** [trippo/ResponsiveFilemanager#612]
Watermark not working if uploaded filename has been transliterated
It cause by line 1426 file UploadHandler.php
line 1426: $name = $file_name ? $file_name : $upload['name'][0];
I fixed it by get file name in file object returned from function handle_file_upload. It's working.
if($file_name) {
            $name = $file_name;
        } elseif(!empty($files[0])) {
            $file = $files[0];
            $name = $file->name;
        } else {
            $name = $upload['name'][0];
        }

**Comment by trippo** [comment]
thanks I will put in next release
