### ISSUE TITLE
YARN build failed

### ISSUE THREAD

**Issue by PoProstuMieciek** [trippo/ResponsiveFilemanager#630]
Hello,
I ran this command and build failed with many errors.
```
yarn install
```
Please, help.
[yarn_install.error.log](https://github.com/trippo/ResponsiveFilemanager/files/5123575/yarn_install.error.log)

**Comment by luasenvy** [comment]
try to [nodejs 10.x](https://nodejs.org/dist/latest-v10.x/) version
i solved same issue
