### ISSUE TITLE
ckeditor support?

### ISSUE THREAD

**Issue by raku** [trippo/ResponsiveFilemanager#66]
can be used with ckeditor?

**Comment by Hell-Raiser** [comment]
+1 for CKEditor plugin. Considering it's a more popular and better editor than TinyMCE is IMHO I am surprised there isn't already a plugin made for it.

**Comment by ldbglobe** [comment]
a small hack in js/include.js seems to solve the callback function

		// small function to extract parameter from url
		function getUrlParam( paramName ) {
			var reParam = new RegExp( '(?:[\?&]|&)' + paramName + '=([^&]+)', 'i' ) ;
			var match = window.location.search.match(reParam) ;
			return ( match && match.length > 1 ) ? match[ 1 ] : null ;
		}

		// if the CKEditorFuncNum added by ckeditor is found so let apply our special effect
		var CKEditorFuncNum = getUrlParam('CKEditorFuncNum');
		if(CKEditorFuncNum)
		{
			window.opener.CKEDITOR.tools.callFunction( CKEditorFuncNum, url );
			window.close();
			return ;
		}

you just have to configure CkEditor by setting browseUrl in your config

    filebrowserBrowseUrl : "filemanager_path/dialog.php?popup=1&type=0&fldr=&field_id=ckeditor",
    filebrowserImageBrowseUrl : ...,
    filebrowserFlashBrowseUrl : ...,
    filebrowserUploadUrl : ...,
    filebrowserImageUploadUrl : ...,
    filebrowserFlashUploadUrl : ...,

popup=1 
=> cause ckeditor open the file manager in a popup window
type=0 
=> set the type you want (see rwdFileManager documentation)
fldr= 
=>  In my application I force loading the root folder
field_id=ckeditor
=> you must pass a non empty string to force rwdFileManager to call the apply fonction

You just have to inject these code after variable initialisation in the apply function (see js/include.js)
And don't forget to generate a minificated version (js/include.min.js) cause only this version is loaded bay dialog.php

	function apply(file,external){

		if ($('#popup').val()==1) 
			var window_parent=window.opener; else var window_parent=window.parent;

		var path = $('#cur_dir').val();
		//path = path.replace('\\', '/');
		var subdir = $('#subdir').val();
		var base_url = $('#base_url').val();
		var alt_name=file.substr(0, file.lastIndexOf('.'));
		var ext=file.split('.').pop();
		ext=ext.toLowerCase();
		var fill='';
		var ext_audio=new Array('ogg','mp3','wav');
		var ext_video=new Array('mp4','ogg','webm');
		var is_return_relative_url = $('#return_relative_url').val();
		var url= encodeURL((is_return_relative_url == 1 ? subdir : base_url+path)+file);

		function getUrlParam( paramName ) {
			var reParam = new RegExp( '(?:[\?&]|&)' + paramName + '=([^&]+)', 'i' ) ;
			var match = window.location.search.match(reParam) ;
			return ( match && match.length > 1 ) ? match[ 1 ] : null ;
		}

		var CKEditorFuncNum = getUrlParam('CKEditorFuncNum');
		if(CKEditorFuncNum)
		{
			window.opener.CKEDITOR.tools.callFunction( CKEditorFuncNum, url );
			window.close();
			return ;
		}

**Comment by bios-ben** [comment]
To be less intrusive I took @ldbglobe code and put it into my application for use via the callback instead. I mass replaced all function calls in include.js from "responsive_filemanager_callback(external)" to "responsive_filemanager_callback(external, url, window.location)". In my application I defined responsive_filemanager_callback to then use those parameters appropriately to set CKEDITOR values.

Suggestion for @trippo 
There's 4 calls to duplicate code for the callback, you should merge this into one call and add an additional check for CKEditorFuncNum. This will give support CKEditor4 with only a few lines of code. I would also recommend passing back the URL in your callback function as it could be useful in some applications.

**Comment by bios-ben** [comment]
Update to my previous post, I found a way to make this happen without modifying any RF code. You need to have a hidden element on your page with a matching ID you send in field_id, and this should relate to your instance ID so you can use the callback to then make the update:
```javascript
// init ckeditor
var config = {toolbar: [...]}; // look at docs if you need CK config
var element = $('#div').get(0); // I'm using jquery, can use native js
var editor = CKEDITOR.inline(element, config); // I happen to be using inline editor, doesn't matter
$('body').append('<input type="hidden" id="'+editor.name+'_url" />'); // callback url for filemanager
editor.config.filebrowserBrowseUrl = '/filemanager-path/dialog.php?popup=1&type=0&fldr=&field_id='+editor.name+'_url'; // pass our unique field to filemanager

// filemanager callback
function responsive_filemanager_callback(field) {
	var instance = field.substr(0, field.length-4); // our instance name is just the field without _url
	if(instance in CKEDITOR.instances) {
		CKEDITOR.tools.callFunction(CKEDITOR.instances[instance]._.filebrowserFn, $('#'+field).val()); // call the filebrowser callback function, same as CKEditorFuncNum passed in URL, using the hidden field we made for the URL value
	} else {
		console.log(field, instance);
		alert("Cannot update CKEditor, please try again and contact technical support if the error persists.");
	}
}
```
This should solve anyone's issue trying to get CKEditor to work.
Note to @trippo I would definitely appreciate the addition of sending the url in the callback as well as the field, don't assume we have an element on the page with an id you can update. If you send back the url we can cleanly reference it instead of needing to append a hidden input to capture it.

**Comment by trippo** [comment]
i release new version with ckeditor integration thanks

**Comment by trippo** [comment]
give me a feedback if work fine
