### ISSUE TITLE
Upload File Error

### ISSUE THREAD

**Issue by samuhay** [trippo/ResponsiveFilemanager#674]
Hi, I am trying to implement FileMegaer for CKEditor and as a Standalone version. So far I can see my images but cannot upload.
Via these settings I can see file names and select one for input that's working only.
![image](https://user-images.githubusercontent.com/14299235/139754312-07ef8a9b-7218-4d02-94c6-083f63434332.png)
![image](https://user-images.githubusercontent.com/14299235/139752127-3f99406d-251d-4cca-8ed6-0fa191d13552.png)
The path of File Menager is htdocs/pulgin/filemanager
The upload path should be htdocs/user/uploads
The thumb path should be htdocs/user/thumbs

This error from url file upload
![image](https://user-images.githubusercontent.com/14299235/139752297-f7953889-db5e-4b74-b364-180f046013ac.png)

This error from local file upload
![image](https://user-images.githubusercontent.com/14299235/139754276-6038583d-1236-4c83-82e4-7d018fa342bc.png)

Can you help me about right file path I am still trying to figure that one. Thank you.

**Comment by samuhay** [comment]
Fixed the implode on UploadHandler.php, it has to be a other way around first exponent than the string. `('.implode(', ',$failed_versions).')
` Now I god Gd error which I open after. New error is like this => 
![image](https://user-images.githubusercontent.com/14299235/139755700-e7e229fb-2283-44b3-be2b-59707032a2d9.png)

**Comment by johntout** [comment]
The warnings indicate that process is trying to get a position of an array of a variable that is null. 

A quick fix is to change Lines 496 and 1429 in UploadHandler.php like below:

$uploaded_bytes = $this->fix_integer_overflow((int)(is_array($content_range) ? $content_range[1] : 0));

**Comment by samuhay** [comment]
![image](https://user-images.githubusercontent.com/14299235/139923479-c7f67d0a-ffc3-4f85-85dc-87703d1a71a7.png)


> The warnings indicate that the process is trying to get a position of an array of a variable that is null.
> 
> A quick fix is to change Lines 496 and 1429 in UploadHandler.php like below:
> 
> $uploaded_bytes = $this->fix_integer_overflow((int)(is_array($content_range) ? $content_range[1] : 0));

**Comment by samuhay** [comment]
Okey, found the solution while looking for time codes. This all errors caused by PHP version.
 First, In config Line 9 changed `mb_http_input('UTF-8');` -> `mb_http_input();`
Second in php_image_magician.php Line 2791 `	if ( ! is_resource($this->imageResized))` -> `	if ( ! is_resource($this->imageResized)  && ! ($this->imageResized instanceof \GdImage))`
Now I can upload iamge and the thumbnail without error. Thanks for all help.
