### ISSUE TITLE
dropzone spritemap.png i18n

### ISSUE THREAD

**Issue by andy5** [trippo/ResponsiveFilemanager#69]
I noticed "spritemap_hu_HU.png" and "spritemap @ 2x_hu_HU.png" files inside "img" directory but apparently they are not connected to the hungarian language, because "spritemap.png" in hard-coded in dopzone.css.

A possible solution is to create css files for different languages to overwrite background images containing texts. Also I don't know the font name used in spritemap.png, maybe it supports english only...

**Comment by ofcerci4826** [comment]
how did you fixed?
