### ISSUE TITLE
Phishing warning for https://www.responsivefilemanager.com/ 

### ISSUE THREAD

**Issue by derhansen** [trippo/ResponsiveFilemanager#710]
Google Chrome reports the website https://www.responsivefilemanager.com/ to be known for phishing attempts.

**Screenshot (german only)**

![image](https://user-images.githubusercontent.com/2629896/233613952-d0ea9638-c177-4bed-8ef4-80d7e17b866f.png)

Please check, if the website has been infected with malware or report an incorrect phishing warning to Google, if this is a false positve.

**Comment by trippo** [comment]
Thanks for reporting
Il 21 apr 2023, 12:30 +0200, Torben Hansen ***@***.***>, ha scritto:

**Comment by derhansen** [comment]
Problem seems to be resolved
